import { defineConfig } from "vite-plus";
import { fileURLToPath, URL } from "node:url";
import vue from "@vitejs/plugin-vue";
import VueRouter from "vue-router/unplugin/vite.mjs";
import ui from "@nuxt/ui/vite";

// Tests use the `vue()` plugin only on purpose: `shallowMount` asserts against
// rendered class names like `.u-badge`. Pulling in `@nuxt/ui` would auto-register
// `UBadge` as a Vue component, so `shallowMount` would stub it as `<u-badge-stub>`
// and the class assertions would stop matching.
const isTest = process.env.VITEST === "true";

// VueRouter (an unplugin) and `@nuxt/ui` return `Plugin<Api>` shapes whose
// generic Api parameter conflicts with `vue()`'s `Plugin<any>` once they
// share an array — vue-tsc bails with TS2321 'Excessive stack depth comparing
// types'. Cast both to `vue()`'s return type to homogenise element types.
// This is a pure type assertion; the runtime values are untouched.
type VuePlugin = ReturnType<typeof vue>;

export default defineConfig({
  plugins: [
    ...(isTest
      ? []
      : ([
          VueRouter({
            routesFolder: "src/pages",
            dts: "src/typed-router.d.ts",
          }),
        ] as VuePlugin[])),
    vue(),
    ...(isTest
      ? []
      : ([
          ui({
            ui: {
              colors: {
                primary: "blue",
                neutral: "zinc",
              },
            },
            autoImport: {
              imports: [
                "vue",
                "vue-router",
                "@vueuse/core",
                {
                  "@unhead/vue": ["useHead"],
                  "@pinia/colada": ["useQuery", "useMutation", "useQueryCache"],
                  pinia: ["defineStore", "storeToRefs"],
                },
              ],
              dirs: ["src/composables/**", "src/utils/**"],
              dts: "src/auto-imports.d.ts",
              vueTemplate: true,
            },
            components: {
              dirs: ["src/components"],
              dts: "src/components.d.ts",
              deep: true,
              // Match Nuxt's auto-component naming: a component in
              // `components/stats/charts/YearlyHeatmap.vue` resolves as
              // `<StatsChartsYearlyHeatmap>` in templates.
              directoryAsNamespace: true,
              collapseSamePrefixes: true,
            },
          }),
        ] as VuePlugin[])),
  ],

  resolve: {
    alias: {
      "~": fileURLToPath(new URL("./src", import.meta.url)),
      "@": fileURLToPath(new URL("./src", import.meta.url)),
    },
  },

  server: {
    port: 3100,
    proxy: {
      "/api": {
        target: "http://localhost:3000",
        changeOrigin: true,
        // Forward WebSocket upgrades too — the realtime bus connects to /api/events.
        ws: true,
      },
    },
  },

  preview: {
    port: 3100,
  },

  build: {
    target: "esnext",
  },

  // Tasks live here (not in package.json) so dependsOn can replace
  // npm-run-all2's `run-p type-check build-only` orchestration. type-check
  // is shared between `build` and `check` — `vp run build` runs vue-tsc
  // first, then the Vite production build; `vp run check` runs vue-tsc
  // first, then `vp check` (oxc fmt+lint+typecheck on .ts files; vue-tsc
  // covers the .vue script blocks oxc can't read).
  run: {
    tasks: {
      dev: {
        command: "vp dev",
        cache: false,
      },
      "type-check": {
        // vue-tsc traverses into @libris/api-hono/client → src/routes/index.ts
        // → src/generated/version.ts. That file is generated by api-hono's
        // generate:version task. Vite+ orders workspace packages by the
        // package.json dep graph for `-r`, but standalone `-F` invocations
        // need an explicit cross-package dependency.
        command: "vue-tsc --build",
        dependsOn: ["@libris/api-hono#generate:version"],
        // Same exclusions as the build task:
        // - .tsbuildinfo: vue-tsc writes it into node_modules/.tmp on every run.
        // - The three .d.ts files: vp build regenerates them with embedded
        //   node_modules/.pnpm/<hash> paths that drift across runs even when
        //   their semantic content is unchanged. Their underlying source
        //   (src/pages, src/composables, src/components) is still tracked
        //   via { auto: true }, so excluding the generated files is safe.
        input: [
          { auto: true },
          "!**/*.tsbuildinfo",
          "!src/typed-router.d.ts",
          "!src/auto-imports.d.ts",
          "!src/components.d.ts",
        ],
      },
      build: {
        command: "vp build",
        // type-check transitively pulls in @libris/api-hono#generate:version,
        // so vp build sees a generated version.ts when it bundles routes
        // imported via @libris/api-hono/client.
        dependsOn: ["type-check"],
        // Exclude self-generated outputs from the input fingerprint:
        // - dist/ is the build output
        // - node_modules/.nuxt-ui/ is codegen written by @nuxt/ui during build
        // - the three .d.ts files are regenerated by vue-router/@nuxt/ui plugins
        //   on every run (configured as their dts targets above)
        input: [
          { auto: true },
          "!dist/**",
          "!node_modules/.nuxt-ui/**",
          "!src/typed-router.d.ts",
          "!src/auto-imports.d.ts",
          "!src/components.d.ts",
        ],
      },
      check: {
        command: "vp check",
        dependsOn: ["type-check"],
      },
      test: {
        command: "vp test run",
        // Loading a TypeScript vite.config makes Vite write a transient
        // `.mjs` into node_modules/.vite-temp/, import it, then delete it.
        // { auto: true } tracks the package dir, so that write lands inside
        // the input set and vp declares the task uncacheable on every run
        // ("read and wrote ... vite.config.ts.timestamp-*.mjs"). Excluding
        // the temp dir lets the test task cache normally.
        input: [{ auto: true }, "!node_modules/.vite-temp/**"],
      },
    },
  },
});
