import { createRoute, OpenAPIHono, z } from "@hono/zod-openapi";
import { eq } from "drizzle-orm";
import { HTTPException } from "hono/http-exception";
import { appSettings, users } from "#db";
import type { AppVariables } from "../../context.js";
import { getLogger } from "../../lib/logger.js";

const logger = getLogger("setup");

/**
 * Marks the install as bootstrapped.
 *
 * It exists to make the emptiness check raceable-safe: `app_settings.key` is a
 * primary key, so two concurrent serializable transactions that both see an
 * empty users table cannot both insert it. Without it there is nothing for the
 * database to serialise on — the check reads rows that do not exist yet, and
 * `users.id` is generated by Better Auth outside our transaction.
 */
const BOOTSTRAP_KEY = "auth.bootstrapped";

/**
 * How long a claim is honoured before it is treated as abandoned.
 *
 * Long enough to cover creating one user, short enough that a crash between
 * claiming and creating does not lock a fresh install out for any length of
 * time worth caring about.
 */
const CLAIM_LEASE_MS = 60_000;

const SetupBody = z
  .object({
    email: z.email().openapi({ description: "Email address for the first admin" }),
    password: z
      .string()
      .min(8)
      .max(128)
      .openapi({ description: "Password for the first admin, at least 8 characters" }),
    name: z.string().min(1).max(200).openapi({ description: "Display name" }),
  })
  .openapi("SetupRequest");

const SetupResponse = z
  .object({
    id: z.string(),
    email: z.string(),
    name: z.string(),
    role: z.string(),
  })
  .openapi("SetupResponse");

const StatusResponse = z
  .object({
    required: z.boolean().openapi({
      description: "True while no user exists, i.e. this install still needs its first admin",
    }),
  })
  .openapi("SetupStatus");

const statusRoute = createRoute({
  method: "get",
  path: "/",
  tags: ["auth"],
  summary: "Whether this install still needs setting up",
  description:
    "Lets the sign-in page decide between offering sign-in and offering first-run setup. Public, " +
    "because there is no account to authenticate with when the answer is yes. Returns a bare " +
    "boolean on purpose — anything richer would be an unauthenticated window into who exists " +
    "on this server.",
  responses: {
    200: {
      description: "Setup status",
      content: { "application/json": { schema: StatusResponse } },
    },
  },
});

const setupRoute = createRoute({
  method: "post",
  path: "/",
  tags: ["auth"],
  summary: "Create the first admin",
  description:
    "First-run bootstrap for a fresh install. Creates the first user with role admin, and only " +
    "while no user exists — every later account is created by an admin, and self-registration " +
    "is disabled. Returns 409 once any user exists, so this is safe to leave mounted.",
  request: {
    body: { content: { "application/json": { schema: SetupBody } }, required: true },
  },
  responses: {
    201: {
      description: "The first admin was created",
      content: { "application/json": { schema: SetupResponse } },
    },
    400: { description: "Invalid request body" },
    409: { description: "Setup has already been completed" },
  },
});

export const setupRoutes = new OpenAPIHono<{ Variables: AppVariables }>()
  .openapi(statusRoute, async (c) => {
    const db = c.get("db");
    const [existing] = await db.select({ id: users.id }).from(users).limit(1);
    return c.json({ required: !existing }, 200);
  })

  .openapi(setupRoute, async (c) => {
    const db = c.get("db");
    const auth = c.get("auth");
    const { email, password, name } = c.req.valid("json");

    // Claim the bootstrap first, in its own serializable transaction. Better
    // Auth writes the user and its credential account through its own adapter,
    // outside any transaction we control, so the claim is what has to be
    // exclusive — not the creation.
    await db
      .transaction(
        async (tx) => {
          const [existing] = await tx.select({ id: users.id }).from(users).limit(1);
          if (existing) {
            throw new HTTPException(409, { message: "Setup already completed" });
          }

          // A live claim means another request is between claiming and
          // creating, so this one loses. It has to be a timed lease rather than
          // a bare flag: the two cases "someone is mid-bootstrap" and "someone
          // crashed mid-bootstrap" look identical otherwise, and treating every
          // leftover claim as stale would let sequentially-executed requests
          // each clear the previous claim and all succeed.
          const [claim] = await tx
            .select()
            .from(appSettings)
            .where(eq(appSettings.key, BOOTSTRAP_KEY))
            .limit(1);
          const claimedAt = (claim?.value as { claimedAt?: number } | undefined)?.claimedAt ?? 0;
          if (Date.now() - claimedAt < CLAIM_LEASE_MS) {
            throw new HTTPException(409, { message: "Setup already completed" });
          }

          await tx.delete(appSettings).where(eq(appSettings.key, BOOTSTRAP_KEY));
          await tx.insert(appSettings).values({
            key: BOOTSTRAP_KEY,
            value: { claimedAt: Date.now() },
          });
        },
        { isolationLevel: "serializable" },
      )
      .catch((err: unknown) => {
        if (err instanceof HTTPException) throw err;
        // A serialization failure or a duplicate BOOTSTRAP_KEY means another
        // request won the race. Same answer either way.
        throw new HTTPException(409, { message: "Setup already completed" });
      });

    try {
      // createUser rather than signUpEmail: sign-up is disabled outright (see
      // emailAndPassword.disableSignUp in lib/auth.ts), and the admin plugin
      // permits a server-side call with no session, which is the only way to
      // create an admin when there is no admin yet.
      const created = await auth.api.createUser({
        body: { email, password, name, role: "admin" },
      });

      logger.info(`First admin created: ${email}`);

      return c.json(
        {
          id: created.user.id,
          email: created.user.email,
          name: created.user.name,
          role: "admin",
        },
        201,
      );
    } catch (err) {
      // Release the claim, or a failed attempt would lock the install out for
      // good with no way back in.
      await db.delete(appSettings).where(eq(appSettings.key, BOOTSTRAP_KEY));
      throw err;
    }
  });
