/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ACCEPTED_BOOK_EXTENSIONS: typeof import("./utils/constants").ACCEPTED_BOOK_EXTENSIONS;
  const ACCEPTED_BOOK_EXTENSION_SET: typeof import("./utils/constants").ACCEPTED_BOOK_EXTENSION_SET;
  const ApiError: typeof import("./composables/useApiClient").ApiError;
  const DEFAULT_PAGE_SIZE: typeof import("./utils/constants").DEFAULT_PAGE_SIZE;
  const EffectScope: typeof import("vue").EffectScope;
  const HARDCOVER_DISABLED_MESSAGE: typeof import("./composables/useHardcoverSearch").HARDCOVER_DISABLED_MESSAGE;
  const MAX_UPLOAD_SIZE_BYTES: typeof import("./utils/constants").MAX_UPLOAD_SIZE_BYTES;
  const SESSIONS_KEY: typeof import("./composables/mutations/useSessionMutations").SESSIONS_KEY;
  const THEMES: typeof import("./composables/useTheme").THEMES;
  const asyncComputed: typeof import("@vueuse/core").asyncComputed;
  const autoResetRef: typeof import("@vueuse/core").autoResetRef;
  const avatarGroupInjectionKey: typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.5.1_@azure+identity@4.13.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@ti_6f01dc82bfdf8523036fdb8ead6c47ba/node_modules/@nuxt/ui/dist/runtime/composables/useAvatarGroup.js").avatarGroupInjectionKey;
  const computed: typeof import("vue").computed;
  const computedAsync: typeof import("@vueuse/core").computedAsync;
  const computedEager: typeof import("@vueuse/core").computedEager;
  const computedInject: typeof import("@vueuse/core").computedInject;
  const computedWithControl: typeof import("@vueuse/core").computedWithControl;
  const controlledComputed: typeof import("@vueuse/core").controlledComputed;
  const controlledRef: typeof import("@vueuse/core").controlledRef;
  const coverUrlSchema: typeof import("./utils/schemas").coverUrlSchema;
  const createApp: typeof import("vue").createApp;
  const createDisposableDirective: typeof import("@vueuse/core").createDisposableDirective;
  const createEventHook: typeof import("@vueuse/core").createEventHook;
  const createGlobalState: typeof import("@vueuse/core").createGlobalState;
  const createInjectionState: typeof import("@vueuse/core").createInjectionState;
  const createReactiveFn: typeof import("@vueuse/core").createReactiveFn;
  const createRef: typeof import("@vueuse/core").createRef;
  const createReusableTemplate: typeof import("@vueuse/core").createReusableTemplate;
  const createSharedComposable: typeof import("@vueuse/core").createSharedComposable;
  const createTemplatePromise: typeof import("@vueuse/core").createTemplatePromise;
  const createUnrefFn: typeof import("@vueuse/core").createUnrefFn;
  const customRef: typeof import("vue").customRef;
  const debouncedRef: typeof import("@vueuse/core").debouncedRef;
  const debouncedWatch: typeof import("@vueuse/core").debouncedWatch;
  const defineAsyncComponent: typeof import("vue").defineAsyncComponent;
  const defineComponent: typeof import("vue").defineComponent;
  const defineLocale: typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.8.1_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_913a7064fdeb5a7a8ca3c073e7097112/node_modules/@nuxt/ui/dist/runtime/composables/defineLocale").defineLocale;
  const defineShortcuts: typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.8.1_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_913a7064fdeb5a7a8ca3c073e7097112/node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts").defineShortcuts;
  const defineStore: typeof import("pinia").defineStore;
  const describeUserAgent: typeof import("./utils/user-agent").describeUserAgent;
  const eagerComputed: typeof import("@vueuse/core").eagerComputed;
  const effectScope: typeof import("vue").effectScope;
  const extendLocale: typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.8.1_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_913a7064fdeb5a7a8ca3c073e7097112/node_modules/@nuxt/ui/dist/runtime/composables/defineLocale").extendLocale;
  const extendRef: typeof import("@vueuse/core").extendRef;
  const extractShortcuts: typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.8.1_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_913a7064fdeb5a7a8ca3c073e7097112/node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts").extractShortcuts;
  const fieldGroupInjectionKey: typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.5.1_@azure+identity@4.13.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@ti_6f01dc82bfdf8523036fdb8ead6c47ba/node_modules/@nuxt/ui/dist/runtime/composables/useFieldGroup.js").fieldGroupInjectionKey;
  const formBusInjectionKey: typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.5.1_@azure+identity@4.13.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@ti_6f01dc82bfdf8523036fdb8ead6c47ba/node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js").formBusInjectionKey;
  const formErrorsInjectionKey: typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.5.1_@azure+identity@4.13.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@ti_6f01dc82bfdf8523036fdb8ead6c47ba/node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js").formErrorsInjectionKey;
  const formFieldInjectionKey: typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.5.1_@azure+identity@4.13.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@ti_6f01dc82bfdf8523036fdb8ead6c47ba/node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js").formFieldInjectionKey;
  const formInputsInjectionKey: typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.5.1_@azure+identity@4.13.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@ti_6f01dc82bfdf8523036fdb8ead6c47ba/node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js").formInputsInjectionKey;
  const formLoadingInjectionKey: typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.5.1_@azure+identity@4.13.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@ti_6f01dc82bfdf8523036fdb8ead6c47ba/node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js").formLoadingInjectionKey;
  const formOptionsInjectionKey: typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.5.1_@azure+identity@4.13.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@ti_6f01dc82bfdf8523036fdb8ead6c47ba/node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js").formOptionsInjectionKey;
  const formStateInjectionKey: typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.5.1_@azure+identity@4.13.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@ti_6f01dc82bfdf8523036fdb8ead6c47ba/node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js").formStateInjectionKey;
  const formatDate: typeof import("./utils/formatters").formatDate;
  const formatFileSize: typeof import("./utils/formatters").formatFileSize;
  const formatTimeAgo: typeof import("./utils/formatters").formatTimeAgo;
  const getCurrentInstance: typeof import("vue").getCurrentInstance;
  const getCurrentScope: typeof import("vue").getCurrentScope;
  const getCurrentWatcher: typeof import("vue").getCurrentWatcher;
  const h: typeof import("vue").h;
  const ignorableWatch: typeof import("@vueuse/core").ignorableWatch;
  const inboxKeys: typeof import("./composables/queries/inboxKeys").inboxKeys;
  const inject: typeof import("vue").inject;
  const injectLocal: typeof import("@vueuse/core").injectLocal;
  const inputIdInjectionKey: typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.5.1_@azure+identity@4.13.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@ti_6f01dc82bfdf8523036fdb8ead6c47ba/node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js").inputIdInjectionKey;
  const isDefined: typeof import("@vueuse/core").isDefined;
  const isProxy: typeof import("vue").isProxy;
  const isReactive: typeof import("vue").isReactive;
  const isReadonly: typeof import("vue").isReadonly;
  const isRef: typeof import("vue").isRef;
  const isShallow: typeof import("vue").isShallow;
  const isbn10Schema: typeof import("./utils/schemas").isbn10Schema;
  const isbn13Schema: typeof import("./utils/schemas").isbn13Schema;
  const kbdKeysMap: typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.5.1_@azure+identity@4.13.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@ti_6f01dc82bfdf8523036fdb8ead6c47ba/node_modules/@nuxt/ui/dist/runtime/composables/useKbd.js").kbdKeysMap;
  const librisConfigKey: typeof import("./composables/useLibrisConfig").librisConfigKey;
  const localeContextInjectionKey: typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.5.1_@azure+identity@4.13.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@ti_6f01dc82bfdf8523036fdb8ead6c47ba/node_modules/@nuxt/ui/dist/runtime/composables/useLocale.js").localeContextInjectionKey;
  const makeDestructurable: typeof import("@vueuse/core").makeDestructurable;
  const markRaw: typeof import("vue").markRaw;
  const nextTick: typeof import("vue").nextTick;
  const onActivated: typeof import("vue").onActivated;
  const onBeforeMount: typeof import("vue").onBeforeMount;
  const onBeforeRouteLeave: typeof import("vue-router").onBeforeRouteLeave;
  const onBeforeRouteUpdate: typeof import("vue-router").onBeforeRouteUpdate;
  const onBeforeUnmount: typeof import("vue").onBeforeUnmount;
  const onBeforeUpdate: typeof import("vue").onBeforeUpdate;
  const onClickOutside: typeof import("@vueuse/core").onClickOutside;
  const onDeactivated: typeof import("vue").onDeactivated;
  const onElementRemoval: typeof import("@vueuse/core").onElementRemoval;
  const onErrorCaptured: typeof import("vue").onErrorCaptured;
  const onKeyStroke: typeof import("@vueuse/core").onKeyStroke;
  const onLongPress: typeof import("@vueuse/core").onLongPress;
  const onMounted: typeof import("vue").onMounted;
  const onRenderTracked: typeof import("vue").onRenderTracked;
  const onRenderTriggered: typeof import("vue").onRenderTriggered;
  const onScopeDispose: typeof import("vue").onScopeDispose;
  const onServerPrefetch: typeof import("vue").onServerPrefetch;
  const onStartTyping: typeof import("@vueuse/core").onStartTyping;
  const onUnmounted: typeof import("vue").onUnmounted;
  const onUpdated: typeof import("vue").onUpdated;
  const onWatcherCleanup: typeof import("vue").onWatcherCleanup;
  const pageCountStringSchema: typeof import("./utils/schemas").pageCountStringSchema;
  const pausableWatch: typeof import("@vueuse/core").pausableWatch;
  const portalTargetInjectionKey: typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.5.1_@azure+identity@4.13.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@ti_6f01dc82bfdf8523036fdb8ead6c47ba/node_modules/@nuxt/ui/dist/runtime/composables/usePortal.js").portalTargetInjectionKey;
  const provide: typeof import("vue").provide;
  const provideLocal: typeof import("@vueuse/core").provideLocal;
  const provideThemeContext: typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.5.1_@azure+identity@4.13.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@ti_6f01dc82bfdf8523036fdb8ead6c47ba/node_modules/@nuxt/ui/dist/runtime/composables/useComponentUI.js").provideThemeContext;
  const reactify: typeof import("@vueuse/core").reactify;
  const reactifyObject: typeof import("@vueuse/core").reactifyObject;
  const reactive: typeof import("vue").reactive;
  const reactiveComputed: typeof import("@vueuse/core").reactiveComputed;
  const reactiveOmit: typeof import("@vueuse/core").reactiveOmit;
  const reactivePick: typeof import("@vueuse/core").reactivePick;
  const readonly: typeof import("vue").readonly;
  const ref: typeof import("vue").ref;
  const refAutoReset: typeof import("@vueuse/core").refAutoReset;
  const refDebounced: typeof import("@vueuse/core").refDebounced;
  const refDefault: typeof import("@vueuse/core").refDefault;
  const refManualReset: typeof import("@vueuse/core").refManualReset;
  const refThrottled: typeof import("@vueuse/core").refThrottled;
  const refWithControl: typeof import("@vueuse/core").refWithControl;
  const resolveComponent: typeof import("vue").resolveComponent;
  const resolveRedirect: typeof import("./utils/redirect").resolveRedirect;
  const resolveRef: typeof import("@vueuse/core").resolveRef;
  const shallowReactive: typeof import("vue").shallowReactive;
  const shallowReadonly: typeof import("vue").shallowReadonly;
  const shallowRef: typeof import("vue").shallowRef;
  const storeToRefs: typeof import("pinia").storeToRefs;
  const syncRef: typeof import("@vueuse/core").syncRef;
  const syncRefs: typeof import("@vueuse/core").syncRefs;
  const templateRef: typeof import("@vueuse/core").templateRef;
  const throttledRef: typeof import("@vueuse/core").throttledRef;
  const throttledWatch: typeof import("@vueuse/core").throttledWatch;
  const toHardcoverSearchError: typeof import("./composables/useHardcoverSearch").toHardcoverSearchError;
  const toRaw: typeof import("vue").toRaw;
  const toReactive: typeof import("@vueuse/core").toReactive;
  const toRef: typeof import("vue").toRef;
  const toRefs: typeof import("vue").toRefs;
  const toValue: typeof import("vue").toValue;
  const toastMaxInjectionKey: typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.5.1_@azure+identity@4.13.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@ti_6f01dc82bfdf8523036fdb8ead6c47ba/node_modules/@nuxt/ui/dist/runtime/composables/useToast.js").toastMaxInjectionKey;
  const triggerRef: typeof import("vue").triggerRef;
  const tryOnBeforeMount: typeof import("@vueuse/core").tryOnBeforeMount;
  const tryOnBeforeUnmount: typeof import("@vueuse/core").tryOnBeforeUnmount;
  const tryOnMounted: typeof import("@vueuse/core").tryOnMounted;
  const tryOnScopeDispose: typeof import("@vueuse/core").tryOnScopeDispose;
  const tryOnUnmounted: typeof import("@vueuse/core").tryOnUnmounted;
  const unref: typeof import("vue").unref;
  const unrefElement: typeof import("@vueuse/core").unrefElement;
  const until: typeof import("@vueuse/core").until;
  const useActiveElement: typeof import("@vueuse/core").useActiveElement;
  const useAnimate: typeof import("@vueuse/core").useAnimate;
  const useApiClient: typeof import("./composables/useApiClient").useApiClient;
  const useApiKeysQuery: typeof import("./composables/mutations/useApiKeyMutations").useApiKeysQuery;
  const useAppConfig: typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.8.1_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_913a7064fdeb5a7a8ca3c073e7097112/node_modules/@nuxt/ui/dist/runtime/vue/composables/useAppConfig.js").useAppConfig;
  const useApplyMetadata: typeof import("./composables/mutations/useBookMutations").useApplyMetadata;
  const useApproveBook: typeof import("./composables/mutations/useBookMutations").useApproveBook;
  const useArrayDifference: typeof import("@vueuse/core").useArrayDifference;
  const useArrayEvery: typeof import("@vueuse/core").useArrayEvery;
  const useArrayFilter: typeof import("@vueuse/core").useArrayFilter;
  const useArrayFind: typeof import("@vueuse/core").useArrayFind;
  const useArrayFindIndex: typeof import("@vueuse/core").useArrayFindIndex;
  const useArrayFindLast: typeof import("@vueuse/core").useArrayFindLast;
  const useArrayIncludes: typeof import("@vueuse/core").useArrayIncludes;
  const useArrayJoin: typeof import("@vueuse/core").useArrayJoin;
  const useArrayMap: typeof import("@vueuse/core").useArrayMap;
  const useArrayReduce: typeof import("@vueuse/core").useArrayReduce;
  const useArraySome: typeof import("@vueuse/core").useArraySome;
  const useArrayUnique: typeof import("@vueuse/core").useArrayUnique;
  const useAsyncQueue: typeof import("@vueuse/core").useAsyncQueue;
  const useAsyncState: typeof import("@vueuse/core").useAsyncState;
  const useAttrs: typeof import("vue").useAttrs;
  const useAuth: typeof import("./composables/useAuth").useAuth;
  const useAvatarGroup: typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.5.1_@azure+identity@4.13.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@ti_6f01dc82bfdf8523036fdb8ead6c47ba/node_modules/@nuxt/ui/dist/runtime/composables/useAvatarGroup.js").useAvatarGroup;
  const useBanUser: typeof import("./composables/mutations/useUserMutations").useBanUser;
  const useBase64: typeof import("@vueuse/core").useBase64;
  const useBattery: typeof import("@vueuse/core").useBattery;
  const useBluetooth: typeof import("@vueuse/core").useBluetooth;
  const useBookCandidatesQuery: typeof import("./composables/queries/useBookDetailQuery").useBookCandidatesQuery;
  const useBookDetailQuery: typeof import("./composables/queries/useBookDetailQuery").useBookDetailQuery;
  const useBookProgressQuery: typeof import("./composables/queries/useBookDetailQuery").useBookProgressQuery;
  const useBreakpoints: typeof import("@vueuse/core").useBreakpoints;
  const useBroadcastChannel: typeof import("@vueuse/core").useBroadcastChannel;
  const useBrowserLocation: typeof import("@vueuse/core").useBrowserLocation;
  const useCached: typeof import("@vueuse/core").useCached;
  const useChangePassword: typeof import("./composables/mutations/useAccountMutations").useChangePassword;
  const useChartTheme: typeof import("./composables/useChartTheme").useChartTheme;
  const useCleanQueue: typeof import("./composables/mutations/useJobMutations").useCleanQueue;
  const useClearReadingStatus: typeof import("./composables/mutations/useBookMutations").useClearReadingStatus;
  const useClipboard: typeof import("@vueuse/core").useClipboard;
  const useClipboardItems: typeof import("@vueuse/core").useClipboardItems;
  const useCloned: typeof import("@vueuse/core").useCloned;
  const useColorMode: typeof import("@vueuse/core").useColorMode;
  const useComponentIcons: typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.5.1_@azure+identity@4.13.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@ti_6f01dc82bfdf8523036fdb8ead6c47ba/node_modules/@nuxt/ui/dist/runtime/composables/useComponentIcons.js").useComponentIcons;
  const useComponentUI: typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.5.1_@azure+identity@4.13.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@ti_6f01dc82bfdf8523036fdb8ead6c47ba/node_modules/@nuxt/ui/dist/runtime/composables/useComponentUI.js").useComponentUI;
  const useConfirmDialog: typeof import("@vueuse/core").useConfirmDialog;
  const useContentSearch: typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.8.1_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_913a7064fdeb5a7a8ca3c073e7097112/node_modules/@nuxt/ui/dist/runtime/composables/useContentSearch").useContentSearch;
  const useCountdown: typeof import("@vueuse/core").useCountdown;
  const useCounter: typeof import("@vueuse/core").useCounter;
  const useCreateApiKey: typeof import("./composables/mutations/useApiKeyMutations").useCreateApiKey;
  const useCreateUser: typeof import("./composables/mutations/useUserMutations").useCreateUser;
  const useCssModule: typeof import("vue").useCssModule;
  const useCssSupports: typeof import("@vueuse/core").useCssSupports;
  const useCssVar: typeof import("@vueuse/core").useCssVar;
  const useCssVars: typeof import("vue").useCssVars;
  const useCurrentElement: typeof import("@vueuse/core").useCurrentElement;
  const useCycleList: typeof import("@vueuse/core").useCycleList;
  const useDark: typeof import("@vueuse/core").useDark;
  const useDashboard: typeof import("./composables/useDashboard").useDashboard;
  const useDashboardQuery: typeof import("./composables/queries/useDashboardQuery").useDashboardQuery;
  const useDateFormat: typeof import("@vueuse/core").useDateFormat;
  const useDebounce: typeof import("@vueuse/core").useDebounce;
  const useDebounceFn: typeof import("@vueuse/core").useDebounceFn;
  const useDebouncedRefHistory: typeof import("@vueuse/core").useDebouncedRefHistory;
  const useDebouncedSearch: typeof import("./composables/useDebouncedSearch").useDebouncedSearch;
  const useDeleteApiKey: typeof import("./composables/mutations/useApiKeyMutations").useDeleteApiKey;
  const useDeleteBook: typeof import("./composables/mutations/useBookMutations").useDeleteBook;
  const useDeleteCredential: typeof import("./composables/mutations/useCredentialMutations").useDeleteCredential;
  const useDeviceMotion: typeof import("@vueuse/core").useDeviceMotion;
  const useDeviceOrientation: typeof import("@vueuse/core").useDeviceOrientation;
  const useDevicePixelRatio: typeof import("@vueuse/core").useDevicePixelRatio;
  const useDevicesList: typeof import("@vueuse/core").useDevicesList;
  const useDisplayMedia: typeof import("@vueuse/core").useDisplayMedia;
  const useDocumentVisibility: typeof import("@vueuse/core").useDocumentVisibility;
  const useDraggable: typeof import("@vueuse/core").useDraggable;
  const useDrainQueue: typeof import("./composables/mutations/useJobMutations").useDrainQueue;
  const useDropZone: typeof import("@vueuse/core").useDropZone;
  const useEditBook: typeof import("./composables/mutations/useBookMutations").useEditBook;
  const useEditorMenu: typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.5.1_@azure+identity@4.13.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@ti_6f01dc82bfdf8523036fdb8ead6c47ba/node_modules/@nuxt/ui/dist/runtime/composables/useEditorMenu.js").useEditorMenu;
  const useElementBounding: typeof import("@vueuse/core").useElementBounding;
  const useElementByPoint: typeof import("@vueuse/core").useElementByPoint;
  const useElementHover: typeof import("@vueuse/core").useElementHover;
  const useElementSize: typeof import("@vueuse/core").useElementSize;
  const useElementVisibility: typeof import("@vueuse/core").useElementVisibility;
  const useEventBus: typeof import("@vueuse/core").useEventBus;
  const useEventListener: typeof import("@vueuse/core").useEventListener;
  const useEventSource: typeof import("@vueuse/core").useEventSource;
  const useEyeDropper: typeof import("@vueuse/core").useEyeDropper;
  const useFailedJobsCountQuery: typeof import("./composables/queries/useSidebarQueries").useFailedJobsCountQuery;
  const useFavicon: typeof import("@vueuse/core").useFavicon;
  const useFetch: typeof import("@vueuse/core").useFetch;
  const useFieldGroup: typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.5.1_@azure+identity@4.13.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@ti_6f01dc82bfdf8523036fdb8ead6c47ba/node_modules/@nuxt/ui/dist/runtime/composables/useFieldGroup.js").useFieldGroup;
  const useFileDialog: typeof import("@vueuse/core").useFileDialog;
  const useFileSystemAccess: typeof import("@vueuse/core").useFileSystemAccess;
  const useFileUpload: typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.8.1_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_913a7064fdeb5a7a8ca3c073e7097112/node_modules/@nuxt/ui/dist/runtime/composables/useFileUpload").useFileUpload;
  const useFocus: typeof import("@vueuse/core").useFocus;
  const useFocusWithin: typeof import("@vueuse/core").useFocusWithin;
  const useFormField: typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.8.1_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_913a7064fdeb5a7a8ca3c073e7097112/node_modules/@nuxt/ui/dist/runtime/composables/useFormField").useFormField;
  const useFps: typeof import("@vueuse/core").useFps;
  const useFullscreen: typeof import("@vueuse/core").useFullscreen;
  const useGamepad: typeof import("@vueuse/core").useGamepad;
  const useGeolocation: typeof import("@vueuse/core").useGeolocation;
  const useHardcoverSearch: typeof import("./composables/useHardcoverSearch").useHardcoverSearch;
  const useHardcoverStatusQuery: typeof import("./composables/queries/useHardcoverStatusQuery").useHardcoverStatusQuery;
  const useHardcoverSyncLogQuery: typeof import("./composables/queries/useHardcoverSyncLogQuery").useHardcoverSyncLogQuery;
  const useHead: typeof import("@unhead/vue").useHead;
  const useId: typeof import("vue").useId;
  const useIdle: typeof import("@vueuse/core").useIdle;
  const useImage: typeof import("@vueuse/core").useImage;
  const useInboxCountQuery: typeof import("./composables/queries/useSidebarQueries").useInboxCountQuery;
  const useInboxDetailQuery: typeof import("./composables/queries/useInboxDetailQuery").useInboxDetailQuery;
  const useInboxListQuery: typeof import("./composables/queries/useInboxQueries").useInboxListQuery;
  const useInboxProcessingQuery: typeof import("./composables/queries/useInboxQueries").useInboxProcessingQuery;
  const useInfiniteScroll: typeof import("@vueuse/core").useInfiniteScroll;
  const useIntersectionObserver: typeof import("@vueuse/core").useIntersectionObserver;
  const useInterval: typeof import("@vueuse/core").useInterval;
  const useIntervalFn: typeof import("@vueuse/core").useIntervalFn;
  const useJobsQuery: typeof import("./composables/queries/useJobsQuery").useJobsQuery;
  const useKbd: typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.8.1_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_913a7064fdeb5a7a8ca3c073e7097112/node_modules/@nuxt/ui/dist/runtime/composables/useKbd").useKbd;
  const useKeyModifier: typeof import("@vueuse/core").useKeyModifier;
  const useLastChanged: typeof import("@vueuse/core").useLastChanged;
  const useLibraryFacetsQuery: typeof import("./composables/queries/useLibraryQueries").useLibraryFacetsQuery;
  const useLibraryListQuery: typeof import("./composables/queries/useLibraryQueries").useLibraryListQuery;
  const useLibrisConfig: typeof import("./composables/useLibrisConfig").useLibrisConfig;
  const useLink: typeof import("vue-router").useLink;
  const useLocalStorage: typeof import("@vueuse/core").useLocalStorage;
  const useLocale: typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.5.1_@azure+identity@4.13.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@ti_6f01dc82bfdf8523036fdb8ead6c47ba/node_modules/@nuxt/ui/dist/runtime/composables/useLocale.js").useLocale;
  const useMagicKeys: typeof import("@vueuse/core").useMagicKeys;
  const useManualRefHistory: typeof import("@vueuse/core").useManualRefHistory;
  const useMediaControls: typeof import("@vueuse/core").useMediaControls;
  const useMediaQuery: typeof import("@vueuse/core").useMediaQuery;
  const useMemoize: typeof import("@vueuse/core").useMemoize;
  const useMemory: typeof import("@vueuse/core").useMemory;
  const useModel: typeof import("vue").useModel;
  const useMounted: typeof import("@vueuse/core").useMounted;
  const useMouse: typeof import("@vueuse/core").useMouse;
  const useMouseInElement: typeof import("@vueuse/core").useMouseInElement;
  const useMousePressed: typeof import("@vueuse/core").useMousePressed;
  const useMutation: typeof import("@pinia/colada").useMutation;
  const useMutationObserver: typeof import("@vueuse/core").useMutationObserver;
  const useNavigatorLanguage: typeof import("@vueuse/core").useNavigatorLanguage;
  const useNetwork: typeof import("@vueuse/core").useNetwork;
  const useNow: typeof import("@vueuse/core").useNow;
  const useObjectUrl: typeof import("@vueuse/core").useObjectUrl;
  const useOffsetPagination: typeof import("@vueuse/core").useOffsetPagination;
  const useOnline: typeof import("@vueuse/core").useOnline;
  const useOverlay: typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.8.1_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_913a7064fdeb5a7a8ca3c073e7097112/node_modules/@nuxt/ui/dist/runtime/composables/useOverlay").useOverlay;
  const usePageLeave: typeof import("@vueuse/core").usePageLeave;
  const useParallax: typeof import("@vueuse/core").useParallax;
  const useParentElement: typeof import("@vueuse/core").useParentElement;
  const usePatchSettings: typeof import("./composables/mutations/useSettingsMutations").usePatchSettings;
  const usePauseQueue: typeof import("./composables/mutations/useJobMutations").usePauseQueue;
  const usePerformanceObserver: typeof import("@vueuse/core").usePerformanceObserver;
  const usePermission: typeof import("@vueuse/core").usePermission;
  const usePointer: typeof import("@vueuse/core").usePointer;
  const usePointerLock: typeof import("@vueuse/core").usePointerLock;
  const usePointerSwipe: typeof import("@vueuse/core").usePointerSwipe;
  const usePortal: typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.5.1_@azure+identity@4.13.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@ti_6f01dc82bfdf8523036fdb8ead6c47ba/node_modules/@nuxt/ui/dist/runtime/composables/usePortal.js").usePortal;
  const usePreferredColorScheme: typeof import("@vueuse/core").usePreferredColorScheme;
  const usePreferredContrast: typeof import("@vueuse/core").usePreferredContrast;
  const usePreferredDark: typeof import("@vueuse/core").usePreferredDark;
  const usePreferredLanguages: typeof import("@vueuse/core").usePreferredLanguages;
  const usePreferredReducedMotion: typeof import("@vueuse/core").usePreferredReducedMotion;
  const usePreferredReducedTransparency: typeof import("@vueuse/core").usePreferredReducedTransparency;
  const usePrevious: typeof import("@vueuse/core").usePrevious;
  const usePutCredential: typeof import("./composables/mutations/useCredentialMutations").usePutCredential;
  const useQuery: typeof import("@pinia/colada").useQuery;
  const useQueryCache: typeof import("@pinia/colada").useQueryCache;
  const useRafFn: typeof import("@vueuse/core").useRafFn;
  const useReadingCountsQuery: typeof import("./composables/queries/useSidebarQueries").useReadingCountsQuery;
  const useReadingQuery: typeof import("./composables/queries/useReadingQuery").useReadingQuery;
  const useRefHistory: typeof import("@vueuse/core").useRefHistory;
  const useRefetchMetadata: typeof import("./composables/mutations/useBookMutations").useRefetchMetadata;
  const useRemoveUser: typeof import("./composables/mutations/useUserMutations").useRemoveUser;
  const useReorganizeBook: typeof import("./composables/mutations/useBookMutations").useReorganizeBook;
  const useRescanBook: typeof import("./composables/mutations/useBookMutations").useRescanBook;
  const useResizable: typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.8.1_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_913a7064fdeb5a7a8ca3c073e7097112/node_modules/@nuxt/ui/dist/runtime/composables/useResizable").useResizable;
  const useResizeObserver: typeof import("@vueuse/core").useResizeObserver;
  const useResumeQueue: typeof import("./composables/mutations/useJobMutations").useResumeQueue;
  const useRetryJob: typeof import("./composables/mutations/useJobMutations").useRetryJob;
  const useRevokeOtherSessions: typeof import("./composables/mutations/useSessionMutations").useRevokeOtherSessions;
  const useRevokeSession: typeof import("./composables/mutations/useSessionMutations").useRevokeSession;
  const useRoute: typeof import("vue-router").useRoute;
  const useRouter: typeof import("vue-router").useRouter;
  const useSSRWidth: typeof import("@vueuse/core").useSSRWidth;
  const useScreenOrientation: typeof import("@vueuse/core").useScreenOrientation;
  const useScreenSafeArea: typeof import("@vueuse/core").useScreenSafeArea;
  const useScriptTag: typeof import("@vueuse/core").useScriptTag;
  const useScroll: typeof import("@vueuse/core").useScroll;
  const useScrollLock: typeof import("@vueuse/core").useScrollLock;
  const useScrollShadow: typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.8.1_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_913a7064fdeb5a7a8ca3c073e7097112/node_modules/@nuxt/ui/dist/runtime/composables/useScrollShadow").useScrollShadow;
  const useScrollspy: typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.8.1_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_913a7064fdeb5a7a8ca3c073e7097112/node_modules/@nuxt/ui/dist/runtime/composables/useScrollspy").useScrollspy;
  const useSearchSuggestQuery: typeof import("./composables/queries/useSearchSuggestQuery").useSearchSuggestQuery;
  const useSeriesDetailQuery: typeof import("./composables/queries/useSeriesQueries").useSeriesDetailQuery;
  const useSeriesListQuery: typeof import("./composables/queries/useSeriesQueries").useSeriesListQuery;
  const useServerEvents: typeof import("./composables/useServerEvents").useServerEvents;
  const useSessionStorage: typeof import("@vueuse/core").useSessionStorage;
  const useSessionsQuery: typeof import("./composables/mutations/useSessionMutations").useSessionsQuery;
  const useSetReadingStatus: typeof import("./composables/mutations/useBookMutations").useSetReadingStatus;
  const useSetUserPassword: typeof import("./composables/mutations/useUserMutations").useSetUserPassword;
  const useSetUserRole: typeof import("./composables/mutations/useUserMutations").useSetUserRole;
  const useSettingsStatusQuery: typeof import("./composables/queries/useSettingsStatusQuery").useSettingsStatusQuery;
  const useSetup: typeof import("./composables/mutations/useApiKeyMutations").useSetup;
  const useShare: typeof import("@vueuse/core").useShare;
  const useSlots: typeof import("vue").useSlots;
  const useSorted: typeof import("@vueuse/core").useSorted;
  const useSpeechRecognition: typeof import("@vueuse/core").useSpeechRecognition;
  const useSpeechSynthesis: typeof import("@vueuse/core").useSpeechSynthesis;
  const useStatsQuery: typeof import("./composables/queries/useStatsQuery").useStatsQuery;
  const useStepper: typeof import("@vueuse/core").useStepper;
  const useStorage: typeof import("@vueuse/core").useStorage;
  const useStorageAsync: typeof import("@vueuse/core").useStorageAsync;
  const useStyleTag: typeof import("@vueuse/core").useStyleTag;
  const useSupported: typeof import("@vueuse/core").useSupported;
  const useSwipe: typeof import("@vueuse/core").useSwipe;
  const useTemplateRef: typeof import("vue").useTemplateRef;
  const useTemplateRefsList: typeof import("@vueuse/core").useTemplateRefsList;
  const useTextDirection: typeof import("@vueuse/core").useTextDirection;
  const useTextSelection: typeof import("@vueuse/core").useTextSelection;
  const useTextareaAutosize: typeof import("@vueuse/core").useTextareaAutosize;
  const useTheme: typeof import("./composables/useTheme").useTheme;
  const useThrottle: typeof import("@vueuse/core").useThrottle;
  const useThrottleFn: typeof import("@vueuse/core").useThrottleFn;
  const useThrottledRefHistory: typeof import("@vueuse/core").useThrottledRefHistory;
  const useTimeAgo: typeof import("@vueuse/core").useTimeAgo;
  const useTimeAgoIntl: typeof import("@vueuse/core").useTimeAgoIntl;
  const useTimeout: typeof import("@vueuse/core").useTimeout;
  const useTimeoutFn: typeof import("@vueuse/core").useTimeoutFn;
  const useTimeoutPoll: typeof import("@vueuse/core").useTimeoutPoll;
  const useTimestamp: typeof import("@vueuse/core").useTimestamp;
  const useTitle: typeof import("@vueuse/core").useTitle;
  const useToNumber: typeof import("@vueuse/core").useToNumber;
  const useToString: typeof import("@vueuse/core").useToString;
  const useToast: typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.8.1_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_913a7064fdeb5a7a8ca3c073e7097112/node_modules/@nuxt/ui/dist/runtime/composables/useToast").useToast;
  const useToggle: typeof import("@vueuse/core").useToggle;
  const useTransition: typeof import("@vueuse/core").useTransition;
  const useTriggerHardcoverSync: typeof import("./composables/mutations/useSettingsMutations").useTriggerHardcoverSync;
  const useUpdateProfile: typeof import("./composables/mutations/useAccountMutations").useUpdateProfile;
  const useUpload: typeof import("./composables/useUpload").useUpload;
  const useUrlSearchParams: typeof import("@vueuse/core").useUrlSearchParams;
  const useUserMedia: typeof import("@vueuse/core").useUserMedia;
  const useUsersQuery: typeof import("./composables/mutations/useUserMutations").useUsersQuery;
  const useVModel: typeof import("@vueuse/core").useVModel;
  const useVModels: typeof import("@vueuse/core").useVModels;
  const useVibrate: typeof import("@vueuse/core").useVibrate;
  const useVirtualList: typeof import("@vueuse/core").useVirtualList;
  const useWakeLock: typeof import("@vueuse/core").useWakeLock;
  const useWebNotification: typeof import("@vueuse/core").useWebNotification;
  const useWebSocket: typeof import("@vueuse/core").useWebSocket;
  const useWebWorker: typeof import("@vueuse/core").useWebWorker;
  const useWebWorkerFn: typeof import("@vueuse/core").useWebWorkerFn;
  const useWindowFocus: typeof import("@vueuse/core").useWindowFocus;
  const useWindowScroll: typeof import("@vueuse/core").useWindowScroll;
  const useWindowSize: typeof import("@vueuse/core").useWindowSize;
  const userAgentIcon: typeof import("./utils/user-agent").userAgentIcon;
  const watch: typeof import("vue").watch;
  const watchArray: typeof import("@vueuse/core").watchArray;
  const watchAtMost: typeof import("@vueuse/core").watchAtMost;
  const watchDebounced: typeof import("@vueuse/core").watchDebounced;
  const watchDeep: typeof import("@vueuse/core").watchDeep;
  const watchEffect: typeof import("vue").watchEffect;
  const watchIgnorable: typeof import("@vueuse/core").watchIgnorable;
  const watchImmediate: typeof import("@vueuse/core").watchImmediate;
  const watchOnce: typeof import("@vueuse/core").watchOnce;
  const watchPausable: typeof import("@vueuse/core").watchPausable;
  const watchPostEffect: typeof import("vue").watchPostEffect;
  const watchSyncEffect: typeof import("vue").watchSyncEffect;
  const watchThrottled: typeof import("@vueuse/core").watchThrottled;
  const watchTriggerable: typeof import("@vueuse/core").watchTriggerable;
  const watchWithFilter: typeof import("@vueuse/core").watchWithFilter;
  const whenever: typeof import("@vueuse/core").whenever;
  const yearStringSchema: typeof import("./utils/schemas").yearStringSchema;
}
// for type re-export
declare global {
  // @ts-ignore
  export type {
    Component,
    Slot,
    Slots,
    ComponentPublicInstance,
    ComputedRef,
    DirectiveBinding,
    ExtractDefaultPropTypes,
    ExtractPropTypes,
    ExtractPublicPropTypes,
    InjectionKey,
    PropType,
    Ref,
    ShallowRef,
    MaybeRef,
    MaybeRefOrGetter,
    VNode,
    WritableComputedRef,
  } from "vue";
  import("vue");
  // @ts-ignore
  export type { ChangePasswordVars } from "./composables/mutations/useAccountMutations";
  import("./composables/mutations/useAccountMutations");
  // @ts-ignore
  export type { DeviceSession } from "./composables/mutations/useSessionMutations";
  import("./composables/mutations/useSessionMutations");
  // @ts-ignore
  export type { ManagedUser } from "./composables/mutations/useUserMutations";
  import("./composables/mutations/useUserMutations");
  // @ts-ignore
  export type { JobFilters } from "./composables/queries/useJobsQuery";
  import("./composables/queries/useJobsQuery");
  // @ts-ignore
  export type { SearchSuggestion } from "./composables/queries/useSearchSuggestQuery";
  import("./composables/queries/useSearchSuggestQuery");
  // @ts-ignore
  export type { ApiError } from "./composables/useApiClient";
  import("./composables/useApiClient");
  // @ts-ignore
  export type { ChartTheme } from "./composables/useChartTheme";
  import("./composables/useChartTheme");
  // @ts-ignore
  export type { HardcoverSearchHit, HardcoverSearchError } from "./composables/useHardcoverSearch";
  import("./composables/useHardcoverSearch");
  // @ts-ignore
  export type { AppConfig } from "./composables/useLibrisConfig";
  import("./composables/useLibrisConfig");
  // @ts-ignore
  export type { EventHandler, ServerEvent } from "./composables/useServerEvents";
  import("./composables/useServerEvents");
  // @ts-ignore
  export type { ThemeValue } from "./composables/useTheme";
  import("./composables/useTheme");
  // @ts-ignore
  export type { UploadResult } from "./composables/useUpload";
  import("./composables/useUpload");
}

// for vue template auto import
import { UnwrapRef } from "vue";
declare module "vue" {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly ACCEPTED_BOOK_EXTENSIONS: UnwrapRef<
      (typeof import("./utils/constants"))["ACCEPTED_BOOK_EXTENSIONS"]
    >;
    readonly ACCEPTED_BOOK_EXTENSION_SET: UnwrapRef<
      (typeof import("./utils/constants"))["ACCEPTED_BOOK_EXTENSION_SET"]
    >;
    readonly ApiError: UnwrapRef<(typeof import("./composables/useApiClient"))["ApiError"]>;
    readonly DEFAULT_PAGE_SIZE: UnwrapRef<
      (typeof import("./utils/constants"))["DEFAULT_PAGE_SIZE"]
    >;
    readonly EffectScope: UnwrapRef<(typeof import("vue"))["EffectScope"]>;
    readonly HARDCOVER_DISABLED_MESSAGE: UnwrapRef<
      (typeof import("./composables/useHardcoverSearch"))["HARDCOVER_DISABLED_MESSAGE"]
    >;
    readonly MAX_UPLOAD_SIZE_BYTES: UnwrapRef<
      (typeof import("./utils/constants"))["MAX_UPLOAD_SIZE_BYTES"]
    >;
    readonly SESSIONS_KEY: UnwrapRef<
      (typeof import("./composables/mutations/useSessionMutations"))["SESSIONS_KEY"]
    >;
    readonly THEMES: UnwrapRef<(typeof import("./composables/useTheme"))["THEMES"]>;
    readonly asyncComputed: UnwrapRef<(typeof import("@vueuse/core"))["asyncComputed"]>;
    readonly autoResetRef: UnwrapRef<(typeof import("@vueuse/core"))["autoResetRef"]>;
    readonly computed: UnwrapRef<(typeof import("vue"))["computed"]>;
    readonly computedAsync: UnwrapRef<(typeof import("@vueuse/core"))["computedAsync"]>;
    readonly computedEager: UnwrapRef<(typeof import("@vueuse/core"))["computedEager"]>;
    readonly computedInject: UnwrapRef<(typeof import("@vueuse/core"))["computedInject"]>;
    readonly computedWithControl: UnwrapRef<(typeof import("@vueuse/core"))["computedWithControl"]>;
    readonly controlledComputed: UnwrapRef<(typeof import("@vueuse/core"))["controlledComputed"]>;
    readonly controlledRef: UnwrapRef<(typeof import("@vueuse/core"))["controlledRef"]>;
    readonly coverUrlSchema: UnwrapRef<(typeof import("./utils/schemas"))["coverUrlSchema"]>;
    readonly createApp: UnwrapRef<(typeof import("vue"))["createApp"]>;
    readonly createDisposableDirective: UnwrapRef<
      (typeof import("@vueuse/core"))["createDisposableDirective"]
    >;
    readonly createEventHook: UnwrapRef<(typeof import("@vueuse/core"))["createEventHook"]>;
    readonly createGlobalState: UnwrapRef<(typeof import("@vueuse/core"))["createGlobalState"]>;
    readonly createInjectionState: UnwrapRef<
      (typeof import("@vueuse/core"))["createInjectionState"]
    >;
    readonly createReactiveFn: UnwrapRef<(typeof import("@vueuse/core"))["createReactiveFn"]>;
    readonly createRef: UnwrapRef<(typeof import("@vueuse/core"))["createRef"]>;
    readonly createReusableTemplate: UnwrapRef<
      (typeof import("@vueuse/core"))["createReusableTemplate"]
    >;
    readonly createSharedComposable: UnwrapRef<
      (typeof import("@vueuse/core"))["createSharedComposable"]
    >;
    readonly createTemplatePromise: UnwrapRef<
      (typeof import("@vueuse/core"))["createTemplatePromise"]
    >;
    readonly createUnrefFn: UnwrapRef<(typeof import("@vueuse/core"))["createUnrefFn"]>;
    readonly customRef: UnwrapRef<(typeof import("vue"))["customRef"]>;
    readonly debouncedRef: UnwrapRef<(typeof import("@vueuse/core"))["debouncedRef"]>;
    readonly debouncedWatch: UnwrapRef<(typeof import("@vueuse/core"))["debouncedWatch"]>;
    readonly defineAsyncComponent: UnwrapRef<(typeof import("vue"))["defineAsyncComponent"]>;
    readonly defineComponent: UnwrapRef<(typeof import("vue"))["defineComponent"]>;
    readonly defineLocale: UnwrapRef<
      (typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.8.1_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_913a7064fdeb5a7a8ca3c073e7097112/node_modules/@nuxt/ui/dist/runtime/composables/defineLocale"))["defineLocale"]
    >;
    readonly defineShortcuts: UnwrapRef<
      (typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.8.1_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_913a7064fdeb5a7a8ca3c073e7097112/node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts"))["defineShortcuts"]
    >;
    readonly defineStore: UnwrapRef<(typeof import("pinia"))["defineStore"]>;
    readonly describeUserAgent: UnwrapRef<
      (typeof import("./utils/user-agent"))["describeUserAgent"]
    >;
    readonly eagerComputed: UnwrapRef<(typeof import("@vueuse/core"))["eagerComputed"]>;
    readonly effectScope: UnwrapRef<(typeof import("vue"))["effectScope"]>;
    readonly extendLocale: UnwrapRef<
      (typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.8.1_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_913a7064fdeb5a7a8ca3c073e7097112/node_modules/@nuxt/ui/dist/runtime/composables/defineLocale"))["extendLocale"]
    >;
    readonly extendRef: UnwrapRef<(typeof import("@vueuse/core"))["extendRef"]>;
    readonly extractShortcuts: UnwrapRef<
      (typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.8.1_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_913a7064fdeb5a7a8ca3c073e7097112/node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts"))["extractShortcuts"]
    >;
    readonly formatDate: UnwrapRef<(typeof import("./utils/formatters"))["formatDate"]>;
    readonly formatFileSize: UnwrapRef<(typeof import("./utils/formatters"))["formatFileSize"]>;
    readonly formatTimeAgo: UnwrapRef<(typeof import("./utils/formatters"))["formatTimeAgo"]>;
    readonly getCurrentInstance: UnwrapRef<(typeof import("vue"))["getCurrentInstance"]>;
    readonly getCurrentScope: UnwrapRef<(typeof import("vue"))["getCurrentScope"]>;
    readonly getCurrentWatcher: UnwrapRef<(typeof import("vue"))["getCurrentWatcher"]>;
    readonly h: UnwrapRef<(typeof import("vue"))["h"]>;
    readonly ignorableWatch: UnwrapRef<(typeof import("@vueuse/core"))["ignorableWatch"]>;
    readonly inboxKeys: UnwrapRef<(typeof import("./composables/queries/inboxKeys"))["inboxKeys"]>;
    readonly inject: UnwrapRef<(typeof import("vue"))["inject"]>;
    readonly injectLocal: UnwrapRef<(typeof import("@vueuse/core"))["injectLocal"]>;
    readonly isDefined: UnwrapRef<(typeof import("@vueuse/core"))["isDefined"]>;
    readonly isProxy: UnwrapRef<(typeof import("vue"))["isProxy"]>;
    readonly isReactive: UnwrapRef<(typeof import("vue"))["isReactive"]>;
    readonly isReadonly: UnwrapRef<(typeof import("vue"))["isReadonly"]>;
    readonly isRef: UnwrapRef<(typeof import("vue"))["isRef"]>;
    readonly isShallow: UnwrapRef<(typeof import("vue"))["isShallow"]>;
    readonly isbn10Schema: UnwrapRef<(typeof import("./utils/schemas"))["isbn10Schema"]>;
    readonly isbn13Schema: UnwrapRef<(typeof import("./utils/schemas"))["isbn13Schema"]>;
    readonly librisConfigKey: UnwrapRef<
      (typeof import("./composables/useLibrisConfig"))["librisConfigKey"]
    >;
    readonly makeDestructurable: UnwrapRef<(typeof import("@vueuse/core"))["makeDestructurable"]>;
    readonly markRaw: UnwrapRef<(typeof import("vue"))["markRaw"]>;
    readonly nextTick: UnwrapRef<(typeof import("vue"))["nextTick"]>;
    readonly onActivated: UnwrapRef<(typeof import("vue"))["onActivated"]>;
    readonly onBeforeMount: UnwrapRef<(typeof import("vue"))["onBeforeMount"]>;
    readonly onBeforeRouteLeave: UnwrapRef<(typeof import("vue-router"))["onBeforeRouteLeave"]>;
    readonly onBeforeRouteUpdate: UnwrapRef<(typeof import("vue-router"))["onBeforeRouteUpdate"]>;
    readonly onBeforeUnmount: UnwrapRef<(typeof import("vue"))["onBeforeUnmount"]>;
    readonly onBeforeUpdate: UnwrapRef<(typeof import("vue"))["onBeforeUpdate"]>;
    readonly onClickOutside: UnwrapRef<(typeof import("@vueuse/core"))["onClickOutside"]>;
    readonly onDeactivated: UnwrapRef<(typeof import("vue"))["onDeactivated"]>;
    readonly onElementRemoval: UnwrapRef<(typeof import("@vueuse/core"))["onElementRemoval"]>;
    readonly onErrorCaptured: UnwrapRef<(typeof import("vue"))["onErrorCaptured"]>;
    readonly onKeyStroke: UnwrapRef<(typeof import("@vueuse/core"))["onKeyStroke"]>;
    readonly onLongPress: UnwrapRef<(typeof import("@vueuse/core"))["onLongPress"]>;
    readonly onMounted: UnwrapRef<(typeof import("vue"))["onMounted"]>;
    readonly onRenderTracked: UnwrapRef<(typeof import("vue"))["onRenderTracked"]>;
    readonly onRenderTriggered: UnwrapRef<(typeof import("vue"))["onRenderTriggered"]>;
    readonly onScopeDispose: UnwrapRef<(typeof import("vue"))["onScopeDispose"]>;
    readonly onServerPrefetch: UnwrapRef<(typeof import("vue"))["onServerPrefetch"]>;
    readonly onStartTyping: UnwrapRef<(typeof import("@vueuse/core"))["onStartTyping"]>;
    readonly onUnmounted: UnwrapRef<(typeof import("vue"))["onUnmounted"]>;
    readonly onUpdated: UnwrapRef<(typeof import("vue"))["onUpdated"]>;
    readonly onWatcherCleanup: UnwrapRef<(typeof import("vue"))["onWatcherCleanup"]>;
    readonly pageCountStringSchema: UnwrapRef<
      (typeof import("./utils/schemas"))["pageCountStringSchema"]
    >;
    readonly pausableWatch: UnwrapRef<(typeof import("@vueuse/core"))["pausableWatch"]>;
    readonly provide: UnwrapRef<(typeof import("vue"))["provide"]>;
    readonly provideLocal: UnwrapRef<(typeof import("@vueuse/core"))["provideLocal"]>;
    readonly reactify: UnwrapRef<(typeof import("@vueuse/core"))["reactify"]>;
    readonly reactifyObject: UnwrapRef<(typeof import("@vueuse/core"))["reactifyObject"]>;
    readonly reactive: UnwrapRef<(typeof import("vue"))["reactive"]>;
    readonly reactiveComputed: UnwrapRef<(typeof import("@vueuse/core"))["reactiveComputed"]>;
    readonly reactiveOmit: UnwrapRef<(typeof import("@vueuse/core"))["reactiveOmit"]>;
    readonly reactivePick: UnwrapRef<(typeof import("@vueuse/core"))["reactivePick"]>;
    readonly readonly: UnwrapRef<(typeof import("vue"))["readonly"]>;
    readonly ref: UnwrapRef<(typeof import("vue"))["ref"]>;
    readonly refAutoReset: UnwrapRef<(typeof import("@vueuse/core"))["refAutoReset"]>;
    readonly refDebounced: UnwrapRef<(typeof import("@vueuse/core"))["refDebounced"]>;
    readonly refDefault: UnwrapRef<(typeof import("@vueuse/core"))["refDefault"]>;
    readonly refManualReset: UnwrapRef<(typeof import("@vueuse/core"))["refManualReset"]>;
    readonly refThrottled: UnwrapRef<(typeof import("@vueuse/core"))["refThrottled"]>;
    readonly refWithControl: UnwrapRef<(typeof import("@vueuse/core"))["refWithControl"]>;
    readonly resolveComponent: UnwrapRef<(typeof import("vue"))["resolveComponent"]>;
    readonly resolveRedirect: UnwrapRef<(typeof import("./utils/redirect"))["resolveRedirect"]>;
    readonly shallowReactive: UnwrapRef<(typeof import("vue"))["shallowReactive"]>;
    readonly shallowReadonly: UnwrapRef<(typeof import("vue"))["shallowReadonly"]>;
    readonly shallowRef: UnwrapRef<(typeof import("vue"))["shallowRef"]>;
    readonly storeToRefs: UnwrapRef<(typeof import("pinia"))["storeToRefs"]>;
    readonly syncRef: UnwrapRef<(typeof import("@vueuse/core"))["syncRef"]>;
    readonly syncRefs: UnwrapRef<(typeof import("@vueuse/core"))["syncRefs"]>;
    readonly templateRef: UnwrapRef<(typeof import("@vueuse/core"))["templateRef"]>;
    readonly throttledRef: UnwrapRef<(typeof import("@vueuse/core"))["throttledRef"]>;
    readonly throttledWatch: UnwrapRef<(typeof import("@vueuse/core"))["throttledWatch"]>;
    readonly toHardcoverSearchError: UnwrapRef<
      (typeof import("./composables/useHardcoverSearch"))["toHardcoverSearchError"]
    >;
    readonly toRaw: UnwrapRef<(typeof import("vue"))["toRaw"]>;
    readonly toReactive: UnwrapRef<(typeof import("@vueuse/core"))["toReactive"]>;
    readonly toRef: UnwrapRef<(typeof import("vue"))["toRef"]>;
    readonly toRefs: UnwrapRef<(typeof import("vue"))["toRefs"]>;
    readonly toValue: UnwrapRef<(typeof import("vue"))["toValue"]>;
    readonly triggerRef: UnwrapRef<(typeof import("vue"))["triggerRef"]>;
    readonly tryOnBeforeMount: UnwrapRef<(typeof import("@vueuse/core"))["tryOnBeforeMount"]>;
    readonly tryOnBeforeUnmount: UnwrapRef<(typeof import("@vueuse/core"))["tryOnBeforeUnmount"]>;
    readonly tryOnMounted: UnwrapRef<(typeof import("@vueuse/core"))["tryOnMounted"]>;
    readonly tryOnScopeDispose: UnwrapRef<(typeof import("@vueuse/core"))["tryOnScopeDispose"]>;
    readonly tryOnUnmounted: UnwrapRef<(typeof import("@vueuse/core"))["tryOnUnmounted"]>;
    readonly unref: UnwrapRef<(typeof import("vue"))["unref"]>;
    readonly unrefElement: UnwrapRef<(typeof import("@vueuse/core"))["unrefElement"]>;
    readonly until: UnwrapRef<(typeof import("@vueuse/core"))["until"]>;
    readonly useActiveElement: UnwrapRef<(typeof import("@vueuse/core"))["useActiveElement"]>;
    readonly useAnimate: UnwrapRef<(typeof import("@vueuse/core"))["useAnimate"]>;
    readonly useApiClient: UnwrapRef<(typeof import("./composables/useApiClient"))["useApiClient"]>;
    readonly useApiKeysQuery: UnwrapRef<
      (typeof import("./composables/mutations/useApiKeyMutations"))["useApiKeysQuery"]
    >;
    readonly useAppConfig: UnwrapRef<
      (typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.8.1_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_913a7064fdeb5a7a8ca3c073e7097112/node_modules/@nuxt/ui/dist/runtime/vue/composables/useAppConfig.js"))["useAppConfig"]
    >;
    readonly useApplyMetadata: UnwrapRef<
      (typeof import("./composables/mutations/useBookMutations"))["useApplyMetadata"]
    >;
    readonly useApproveBook: UnwrapRef<
      (typeof import("./composables/mutations/useBookMutations"))["useApproveBook"]
    >;
    readonly useArrayDifference: UnwrapRef<(typeof import("@vueuse/core"))["useArrayDifference"]>;
    readonly useArrayEvery: UnwrapRef<(typeof import("@vueuse/core"))["useArrayEvery"]>;
    readonly useArrayFilter: UnwrapRef<(typeof import("@vueuse/core"))["useArrayFilter"]>;
    readonly useArrayFind: UnwrapRef<(typeof import("@vueuse/core"))["useArrayFind"]>;
    readonly useArrayFindIndex: UnwrapRef<(typeof import("@vueuse/core"))["useArrayFindIndex"]>;
    readonly useArrayFindLast: UnwrapRef<(typeof import("@vueuse/core"))["useArrayFindLast"]>;
    readonly useArrayIncludes: UnwrapRef<(typeof import("@vueuse/core"))["useArrayIncludes"]>;
    readonly useArrayJoin: UnwrapRef<(typeof import("@vueuse/core"))["useArrayJoin"]>;
    readonly useArrayMap: UnwrapRef<(typeof import("@vueuse/core"))["useArrayMap"]>;
    readonly useArrayReduce: UnwrapRef<(typeof import("@vueuse/core"))["useArrayReduce"]>;
    readonly useArraySome: UnwrapRef<(typeof import("@vueuse/core"))["useArraySome"]>;
    readonly useArrayUnique: UnwrapRef<(typeof import("@vueuse/core"))["useArrayUnique"]>;
    readonly useAsyncQueue: UnwrapRef<(typeof import("@vueuse/core"))["useAsyncQueue"]>;
    readonly useAsyncState: UnwrapRef<(typeof import("@vueuse/core"))["useAsyncState"]>;
    readonly useAttrs: UnwrapRef<(typeof import("vue"))["useAttrs"]>;
    readonly useAuth: UnwrapRef<(typeof import("./composables/useAuth"))["useAuth"]>;
    readonly useBanUser: UnwrapRef<
      (typeof import("./composables/mutations/useUserMutations"))["useBanUser"]
    >;
    readonly useBase64: UnwrapRef<(typeof import("@vueuse/core"))["useBase64"]>;
    readonly useBattery: UnwrapRef<(typeof import("@vueuse/core"))["useBattery"]>;
    readonly useBluetooth: UnwrapRef<(typeof import("@vueuse/core"))["useBluetooth"]>;
    readonly useBookCandidatesQuery: UnwrapRef<
      (typeof import("./composables/queries/useBookDetailQuery"))["useBookCandidatesQuery"]
    >;
    readonly useBookDetailQuery: UnwrapRef<
      (typeof import("./composables/queries/useBookDetailQuery"))["useBookDetailQuery"]
    >;
    readonly useBookProgressQuery: UnwrapRef<
      (typeof import("./composables/queries/useBookDetailQuery"))["useBookProgressQuery"]
    >;
    readonly useBreakpoints: UnwrapRef<(typeof import("@vueuse/core"))["useBreakpoints"]>;
    readonly useBroadcastChannel: UnwrapRef<(typeof import("@vueuse/core"))["useBroadcastChannel"]>;
    readonly useBrowserLocation: UnwrapRef<(typeof import("@vueuse/core"))["useBrowserLocation"]>;
    readonly useCached: UnwrapRef<(typeof import("@vueuse/core"))["useCached"]>;
    readonly useChangePassword: UnwrapRef<
      (typeof import("./composables/mutations/useAccountMutations"))["useChangePassword"]
    >;
    readonly useChartTheme: UnwrapRef<
      (typeof import("./composables/useChartTheme"))["useChartTheme"]
    >;
    readonly useCleanQueue: UnwrapRef<
      (typeof import("./composables/mutations/useJobMutations"))["useCleanQueue"]
    >;
    readonly useClearReadingStatus: UnwrapRef<
      (typeof import("./composables/mutations/useBookMutations"))["useClearReadingStatus"]
    >;
    readonly useClipboard: UnwrapRef<(typeof import("@vueuse/core"))["useClipboard"]>;
    readonly useClipboardItems: UnwrapRef<(typeof import("@vueuse/core"))["useClipboardItems"]>;
    readonly useCloned: UnwrapRef<(typeof import("@vueuse/core"))["useCloned"]>;
    readonly useColorMode: UnwrapRef<(typeof import("@vueuse/core"))["useColorMode"]>;
    readonly useConfirmDialog: UnwrapRef<(typeof import("@vueuse/core"))["useConfirmDialog"]>;
    readonly useContentSearch: UnwrapRef<
      (typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.8.1_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_913a7064fdeb5a7a8ca3c073e7097112/node_modules/@nuxt/ui/dist/runtime/composables/useContentSearch"))["useContentSearch"]
    >;
    readonly useCountdown: UnwrapRef<(typeof import("@vueuse/core"))["useCountdown"]>;
    readonly useCounter: UnwrapRef<(typeof import("@vueuse/core"))["useCounter"]>;
    readonly useCreateApiKey: UnwrapRef<
      (typeof import("./composables/mutations/useApiKeyMutations"))["useCreateApiKey"]
    >;
    readonly useCreateUser: UnwrapRef<
      (typeof import("./composables/mutations/useUserMutations"))["useCreateUser"]
    >;
    readonly useCssModule: UnwrapRef<(typeof import("vue"))["useCssModule"]>;
    readonly useCssSupports: UnwrapRef<(typeof import("@vueuse/core"))["useCssSupports"]>;
    readonly useCssVar: UnwrapRef<(typeof import("@vueuse/core"))["useCssVar"]>;
    readonly useCssVars: UnwrapRef<(typeof import("vue"))["useCssVars"]>;
    readonly useCurrentElement: UnwrapRef<(typeof import("@vueuse/core"))["useCurrentElement"]>;
    readonly useCycleList: UnwrapRef<(typeof import("@vueuse/core"))["useCycleList"]>;
    readonly useDark: UnwrapRef<(typeof import("@vueuse/core"))["useDark"]>;
    readonly useDashboard: UnwrapRef<(typeof import("./composables/useDashboard"))["useDashboard"]>;
    readonly useDashboardQuery: UnwrapRef<
      (typeof import("./composables/queries/useDashboardQuery"))["useDashboardQuery"]
    >;
    readonly useDateFormat: UnwrapRef<(typeof import("@vueuse/core"))["useDateFormat"]>;
    readonly useDebounce: UnwrapRef<(typeof import("@vueuse/core"))["useDebounce"]>;
    readonly useDebounceFn: UnwrapRef<(typeof import("@vueuse/core"))["useDebounceFn"]>;
    readonly useDebouncedRefHistory: UnwrapRef<
      (typeof import("@vueuse/core"))["useDebouncedRefHistory"]
    >;
    readonly useDebouncedSearch: UnwrapRef<
      (typeof import("./composables/useDebouncedSearch"))["useDebouncedSearch"]
    >;
    readonly useDeleteApiKey: UnwrapRef<
      (typeof import("./composables/mutations/useApiKeyMutations"))["useDeleteApiKey"]
    >;
    readonly useDeleteBook: UnwrapRef<
      (typeof import("./composables/mutations/useBookMutations"))["useDeleteBook"]
    >;
    readonly useDeleteCredential: UnwrapRef<
      (typeof import("./composables/mutations/useCredentialMutations"))["useDeleteCredential"]
    >;
    readonly useDeviceMotion: UnwrapRef<(typeof import("@vueuse/core"))["useDeviceMotion"]>;
    readonly useDeviceOrientation: UnwrapRef<
      (typeof import("@vueuse/core"))["useDeviceOrientation"]
    >;
    readonly useDevicePixelRatio: UnwrapRef<(typeof import("@vueuse/core"))["useDevicePixelRatio"]>;
    readonly useDevicesList: UnwrapRef<(typeof import("@vueuse/core"))["useDevicesList"]>;
    readonly useDisplayMedia: UnwrapRef<(typeof import("@vueuse/core"))["useDisplayMedia"]>;
    readonly useDocumentVisibility: UnwrapRef<
      (typeof import("@vueuse/core"))["useDocumentVisibility"]
    >;
    readonly useDraggable: UnwrapRef<(typeof import("@vueuse/core"))["useDraggable"]>;
    readonly useDrainQueue: UnwrapRef<
      (typeof import("./composables/mutations/useJobMutations"))["useDrainQueue"]
    >;
    readonly useDropZone: UnwrapRef<(typeof import("@vueuse/core"))["useDropZone"]>;
    readonly useEditBook: UnwrapRef<
      (typeof import("./composables/mutations/useBookMutations"))["useEditBook"]
    >;
    readonly useElementBounding: UnwrapRef<(typeof import("@vueuse/core"))["useElementBounding"]>;
    readonly useElementByPoint: UnwrapRef<(typeof import("@vueuse/core"))["useElementByPoint"]>;
    readonly useElementHover: UnwrapRef<(typeof import("@vueuse/core"))["useElementHover"]>;
    readonly useElementSize: UnwrapRef<(typeof import("@vueuse/core"))["useElementSize"]>;
    readonly useElementVisibility: UnwrapRef<
      (typeof import("@vueuse/core"))["useElementVisibility"]
    >;
    readonly useEventBus: UnwrapRef<(typeof import("@vueuse/core"))["useEventBus"]>;
    readonly useEventListener: UnwrapRef<(typeof import("@vueuse/core"))["useEventListener"]>;
    readonly useEventSource: UnwrapRef<(typeof import("@vueuse/core"))["useEventSource"]>;
    readonly useEyeDropper: UnwrapRef<(typeof import("@vueuse/core"))["useEyeDropper"]>;
    readonly useFailedJobsCountQuery: UnwrapRef<
      (typeof import("./composables/queries/useSidebarQueries"))["useFailedJobsCountQuery"]
    >;
    readonly useFavicon: UnwrapRef<(typeof import("@vueuse/core"))["useFavicon"]>;
    readonly useFetch: UnwrapRef<(typeof import("@vueuse/core"))["useFetch"]>;
    readonly useFileDialog: UnwrapRef<(typeof import("@vueuse/core"))["useFileDialog"]>;
    readonly useFileSystemAccess: UnwrapRef<(typeof import("@vueuse/core"))["useFileSystemAccess"]>;
    readonly useFileUpload: UnwrapRef<
      (typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.8.1_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_913a7064fdeb5a7a8ca3c073e7097112/node_modules/@nuxt/ui/dist/runtime/composables/useFileUpload"))["useFileUpload"]
    >;
    readonly useFocus: UnwrapRef<(typeof import("@vueuse/core"))["useFocus"]>;
    readonly useFocusWithin: UnwrapRef<(typeof import("@vueuse/core"))["useFocusWithin"]>;
    readonly useFormField: UnwrapRef<
      (typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.8.1_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_913a7064fdeb5a7a8ca3c073e7097112/node_modules/@nuxt/ui/dist/runtime/composables/useFormField"))["useFormField"]
    >;
    readonly useFps: UnwrapRef<(typeof import("@vueuse/core"))["useFps"]>;
    readonly useFullscreen: UnwrapRef<(typeof import("@vueuse/core"))["useFullscreen"]>;
    readonly useGamepad: UnwrapRef<(typeof import("@vueuse/core"))["useGamepad"]>;
    readonly useGeolocation: UnwrapRef<(typeof import("@vueuse/core"))["useGeolocation"]>;
    readonly useHardcoverSearch: UnwrapRef<
      (typeof import("./composables/useHardcoverSearch"))["useHardcoverSearch"]
    >;
    readonly useHardcoverStatusQuery: UnwrapRef<
      (typeof import("./composables/queries/useHardcoverStatusQuery"))["useHardcoverStatusQuery"]
    >;
    readonly useHardcoverSyncLogQuery: UnwrapRef<
      (typeof import("./composables/queries/useHardcoverSyncLogQuery"))["useHardcoverSyncLogQuery"]
    >;
    readonly useHead: UnwrapRef<(typeof import("@unhead/vue"))["useHead"]>;
    readonly useId: UnwrapRef<(typeof import("vue"))["useId"]>;
    readonly useIdle: UnwrapRef<(typeof import("@vueuse/core"))["useIdle"]>;
    readonly useImage: UnwrapRef<(typeof import("@vueuse/core"))["useImage"]>;
    readonly useInboxCountQuery: UnwrapRef<
      (typeof import("./composables/queries/useSidebarQueries"))["useInboxCountQuery"]
    >;
    readonly useInboxDetailQuery: UnwrapRef<
      (typeof import("./composables/queries/useInboxDetailQuery"))["useInboxDetailQuery"]
    >;
    readonly useInboxListQuery: UnwrapRef<
      (typeof import("./composables/queries/useInboxQueries"))["useInboxListQuery"]
    >;
    readonly useInboxProcessingQuery: UnwrapRef<
      (typeof import("./composables/queries/useInboxQueries"))["useInboxProcessingQuery"]
    >;
    readonly useInfiniteScroll: UnwrapRef<(typeof import("@vueuse/core"))["useInfiniteScroll"]>;
    readonly useIntersectionObserver: UnwrapRef<
      (typeof import("@vueuse/core"))["useIntersectionObserver"]
    >;
    readonly useInterval: UnwrapRef<(typeof import("@vueuse/core"))["useInterval"]>;
    readonly useIntervalFn: UnwrapRef<(typeof import("@vueuse/core"))["useIntervalFn"]>;
    readonly useJobsQuery: UnwrapRef<
      (typeof import("./composables/queries/useJobsQuery"))["useJobsQuery"]
    >;
    readonly useKbd: UnwrapRef<
      (typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.8.1_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_913a7064fdeb5a7a8ca3c073e7097112/node_modules/@nuxt/ui/dist/runtime/composables/useKbd"))["useKbd"]
    >;
    readonly useKeyModifier: UnwrapRef<(typeof import("@vueuse/core"))["useKeyModifier"]>;
    readonly useLastChanged: UnwrapRef<(typeof import("@vueuse/core"))["useLastChanged"]>;
    readonly useLibraryFacetsQuery: UnwrapRef<
      (typeof import("./composables/queries/useLibraryQueries"))["useLibraryFacetsQuery"]
    >;
    readonly useLibraryListQuery: UnwrapRef<
      (typeof import("./composables/queries/useLibraryQueries"))["useLibraryListQuery"]
    >;
    readonly useLibrisConfig: UnwrapRef<
      (typeof import("./composables/useLibrisConfig"))["useLibrisConfig"]
    >;
    readonly useLink: UnwrapRef<(typeof import("vue-router"))["useLink"]>;
    readonly useLocalStorage: UnwrapRef<(typeof import("@vueuse/core"))["useLocalStorage"]>;
    readonly useMagicKeys: UnwrapRef<(typeof import("@vueuse/core"))["useMagicKeys"]>;
    readonly useManualRefHistory: UnwrapRef<(typeof import("@vueuse/core"))["useManualRefHistory"]>;
    readonly useMediaControls: UnwrapRef<(typeof import("@vueuse/core"))["useMediaControls"]>;
    readonly useMediaQuery: UnwrapRef<(typeof import("@vueuse/core"))["useMediaQuery"]>;
    readonly useMemoize: UnwrapRef<(typeof import("@vueuse/core"))["useMemoize"]>;
    readonly useMemory: UnwrapRef<(typeof import("@vueuse/core"))["useMemory"]>;
    readonly useModel: UnwrapRef<(typeof import("vue"))["useModel"]>;
    readonly useMounted: UnwrapRef<(typeof import("@vueuse/core"))["useMounted"]>;
    readonly useMouse: UnwrapRef<(typeof import("@vueuse/core"))["useMouse"]>;
    readonly useMouseInElement: UnwrapRef<(typeof import("@vueuse/core"))["useMouseInElement"]>;
    readonly useMousePressed: UnwrapRef<(typeof import("@vueuse/core"))["useMousePressed"]>;
    readonly useMutation: UnwrapRef<(typeof import("@pinia/colada"))["useMutation"]>;
    readonly useMutationObserver: UnwrapRef<(typeof import("@vueuse/core"))["useMutationObserver"]>;
    readonly useNavigatorLanguage: UnwrapRef<
      (typeof import("@vueuse/core"))["useNavigatorLanguage"]
    >;
    readonly useNetwork: UnwrapRef<(typeof import("@vueuse/core"))["useNetwork"]>;
    readonly useNow: UnwrapRef<(typeof import("@vueuse/core"))["useNow"]>;
    readonly useObjectUrl: UnwrapRef<(typeof import("@vueuse/core"))["useObjectUrl"]>;
    readonly useOffsetPagination: UnwrapRef<(typeof import("@vueuse/core"))["useOffsetPagination"]>;
    readonly useOnline: UnwrapRef<(typeof import("@vueuse/core"))["useOnline"]>;
    readonly useOverlay: UnwrapRef<
      (typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.8.1_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_913a7064fdeb5a7a8ca3c073e7097112/node_modules/@nuxt/ui/dist/runtime/composables/useOverlay"))["useOverlay"]
    >;
    readonly usePageLeave: UnwrapRef<(typeof import("@vueuse/core"))["usePageLeave"]>;
    readonly useParallax: UnwrapRef<(typeof import("@vueuse/core"))["useParallax"]>;
    readonly useParentElement: UnwrapRef<(typeof import("@vueuse/core"))["useParentElement"]>;
    readonly usePatchSettings: UnwrapRef<
      (typeof import("./composables/mutations/useSettingsMutations"))["usePatchSettings"]
    >;
    readonly usePauseQueue: UnwrapRef<
      (typeof import("./composables/mutations/useJobMutations"))["usePauseQueue"]
    >;
    readonly usePerformanceObserver: UnwrapRef<
      (typeof import("@vueuse/core"))["usePerformanceObserver"]
    >;
    readonly usePermission: UnwrapRef<(typeof import("@vueuse/core"))["usePermission"]>;
    readonly usePointer: UnwrapRef<(typeof import("@vueuse/core"))["usePointer"]>;
    readonly usePointerLock: UnwrapRef<(typeof import("@vueuse/core"))["usePointerLock"]>;
    readonly usePointerSwipe: UnwrapRef<(typeof import("@vueuse/core"))["usePointerSwipe"]>;
    readonly usePreferredColorScheme: UnwrapRef<
      (typeof import("@vueuse/core"))["usePreferredColorScheme"]
    >;
    readonly usePreferredContrast: UnwrapRef<
      (typeof import("@vueuse/core"))["usePreferredContrast"]
    >;
    readonly usePreferredDark: UnwrapRef<(typeof import("@vueuse/core"))["usePreferredDark"]>;
    readonly usePreferredLanguages: UnwrapRef<
      (typeof import("@vueuse/core"))["usePreferredLanguages"]
    >;
    readonly usePreferredReducedMotion: UnwrapRef<
      (typeof import("@vueuse/core"))["usePreferredReducedMotion"]
    >;
    readonly usePreferredReducedTransparency: UnwrapRef<
      (typeof import("@vueuse/core"))["usePreferredReducedTransparency"]
    >;
    readonly usePrevious: UnwrapRef<(typeof import("@vueuse/core"))["usePrevious"]>;
    readonly usePutCredential: UnwrapRef<
      (typeof import("./composables/mutations/useCredentialMutations"))["usePutCredential"]
    >;
    readonly useQuery: UnwrapRef<(typeof import("@pinia/colada"))["useQuery"]>;
    readonly useQueryCache: UnwrapRef<(typeof import("@pinia/colada"))["useQueryCache"]>;
    readonly useRafFn: UnwrapRef<(typeof import("@vueuse/core"))["useRafFn"]>;
    readonly useReadingCountsQuery: UnwrapRef<
      (typeof import("./composables/queries/useSidebarQueries"))["useReadingCountsQuery"]
    >;
    readonly useReadingQuery: UnwrapRef<
      (typeof import("./composables/queries/useReadingQuery"))["useReadingQuery"]
    >;
    readonly useRefHistory: UnwrapRef<(typeof import("@vueuse/core"))["useRefHistory"]>;
    readonly useRefetchMetadata: UnwrapRef<
      (typeof import("./composables/mutations/useBookMutations"))["useRefetchMetadata"]
    >;
    readonly useRemoveUser: UnwrapRef<
      (typeof import("./composables/mutations/useUserMutations"))["useRemoveUser"]
    >;
    readonly useReorganizeBook: UnwrapRef<
      (typeof import("./composables/mutations/useBookMutations"))["useReorganizeBook"]
    >;
    readonly useRescanBook: UnwrapRef<
      (typeof import("./composables/mutations/useBookMutations"))["useRescanBook"]
    >;
    readonly useResizable: UnwrapRef<
      (typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.8.1_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_913a7064fdeb5a7a8ca3c073e7097112/node_modules/@nuxt/ui/dist/runtime/composables/useResizable"))["useResizable"]
    >;
    readonly useResizeObserver: UnwrapRef<(typeof import("@vueuse/core"))["useResizeObserver"]>;
    readonly useResumeQueue: UnwrapRef<
      (typeof import("./composables/mutations/useJobMutations"))["useResumeQueue"]
    >;
    readonly useRetryJob: UnwrapRef<
      (typeof import("./composables/mutations/useJobMutations"))["useRetryJob"]
    >;
    readonly useRevokeOtherSessions: UnwrapRef<
      (typeof import("./composables/mutations/useSessionMutations"))["useRevokeOtherSessions"]
    >;
    readonly useRevokeSession: UnwrapRef<
      (typeof import("./composables/mutations/useSessionMutations"))["useRevokeSession"]
    >;
    readonly useRoute: UnwrapRef<(typeof import("vue-router"))["useRoute"]>;
    readonly useRouter: UnwrapRef<(typeof import("vue-router"))["useRouter"]>;
    readonly useSSRWidth: UnwrapRef<(typeof import("@vueuse/core"))["useSSRWidth"]>;
    readonly useScreenOrientation: UnwrapRef<
      (typeof import("@vueuse/core"))["useScreenOrientation"]
    >;
    readonly useScreenSafeArea: UnwrapRef<(typeof import("@vueuse/core"))["useScreenSafeArea"]>;
    readonly useScriptTag: UnwrapRef<(typeof import("@vueuse/core"))["useScriptTag"]>;
    readonly useScroll: UnwrapRef<(typeof import("@vueuse/core"))["useScroll"]>;
    readonly useScrollLock: UnwrapRef<(typeof import("@vueuse/core"))["useScrollLock"]>;
    readonly useScrollShadow: UnwrapRef<
      (typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.8.1_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_913a7064fdeb5a7a8ca3c073e7097112/node_modules/@nuxt/ui/dist/runtime/composables/useScrollShadow"))["useScrollShadow"]
    >;
    readonly useScrollspy: UnwrapRef<
      (typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.8.1_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_913a7064fdeb5a7a8ca3c073e7097112/node_modules/@nuxt/ui/dist/runtime/composables/useScrollspy"))["useScrollspy"]
    >;
    readonly useSearchSuggestQuery: UnwrapRef<
      (typeof import("./composables/queries/useSearchSuggestQuery"))["useSearchSuggestQuery"]
    >;
    readonly useSeriesDetailQuery: UnwrapRef<
      (typeof import("./composables/queries/useSeriesQueries"))["useSeriesDetailQuery"]
    >;
    readonly useSeriesListQuery: UnwrapRef<
      (typeof import("./composables/queries/useSeriesQueries"))["useSeriesListQuery"]
    >;
    readonly useServerEvents: UnwrapRef<
      (typeof import("./composables/useServerEvents"))["useServerEvents"]
    >;
    readonly useSessionStorage: UnwrapRef<(typeof import("@vueuse/core"))["useSessionStorage"]>;
    readonly useSessionsQuery: UnwrapRef<
      (typeof import("./composables/mutations/useSessionMutations"))["useSessionsQuery"]
    >;
    readonly useSetReadingStatus: UnwrapRef<
      (typeof import("./composables/mutations/useBookMutations"))["useSetReadingStatus"]
    >;
    readonly useSetUserPassword: UnwrapRef<
      (typeof import("./composables/mutations/useUserMutations"))["useSetUserPassword"]
    >;
    readonly useSetUserRole: UnwrapRef<
      (typeof import("./composables/mutations/useUserMutations"))["useSetUserRole"]
    >;
    readonly useSettingsStatusQuery: UnwrapRef<
      (typeof import("./composables/queries/useSettingsStatusQuery"))["useSettingsStatusQuery"]
    >;
    readonly useSetup: UnwrapRef<
      (typeof import("./composables/mutations/useApiKeyMutations"))["useSetup"]
    >;
    readonly useShare: UnwrapRef<(typeof import("@vueuse/core"))["useShare"]>;
    readonly useSlots: UnwrapRef<(typeof import("vue"))["useSlots"]>;
    readonly useSorted: UnwrapRef<(typeof import("@vueuse/core"))["useSorted"]>;
    readonly useSpeechRecognition: UnwrapRef<
      (typeof import("@vueuse/core"))["useSpeechRecognition"]
    >;
    readonly useSpeechSynthesis: UnwrapRef<(typeof import("@vueuse/core"))["useSpeechSynthesis"]>;
    readonly useStatsQuery: UnwrapRef<
      (typeof import("./composables/queries/useStatsQuery"))["useStatsQuery"]
    >;
    readonly useStepper: UnwrapRef<(typeof import("@vueuse/core"))["useStepper"]>;
    readonly useStorage: UnwrapRef<(typeof import("@vueuse/core"))["useStorage"]>;
    readonly useStorageAsync: UnwrapRef<(typeof import("@vueuse/core"))["useStorageAsync"]>;
    readonly useStyleTag: UnwrapRef<(typeof import("@vueuse/core"))["useStyleTag"]>;
    readonly useSupported: UnwrapRef<(typeof import("@vueuse/core"))["useSupported"]>;
    readonly useSwipe: UnwrapRef<(typeof import("@vueuse/core"))["useSwipe"]>;
    readonly useTemplateRef: UnwrapRef<(typeof import("vue"))["useTemplateRef"]>;
    readonly useTemplateRefsList: UnwrapRef<(typeof import("@vueuse/core"))["useTemplateRefsList"]>;
    readonly useTextDirection: UnwrapRef<(typeof import("@vueuse/core"))["useTextDirection"]>;
    readonly useTextSelection: UnwrapRef<(typeof import("@vueuse/core"))["useTextSelection"]>;
    readonly useTextareaAutosize: UnwrapRef<(typeof import("@vueuse/core"))["useTextareaAutosize"]>;
    readonly useTheme: UnwrapRef<(typeof import("./composables/useTheme"))["useTheme"]>;
    readonly useThrottle: UnwrapRef<(typeof import("@vueuse/core"))["useThrottle"]>;
    readonly useThrottleFn: UnwrapRef<(typeof import("@vueuse/core"))["useThrottleFn"]>;
    readonly useThrottledRefHistory: UnwrapRef<
      (typeof import("@vueuse/core"))["useThrottledRefHistory"]
    >;
    readonly useTimeAgo: UnwrapRef<(typeof import("@vueuse/core"))["useTimeAgo"]>;
    readonly useTimeAgoIntl: UnwrapRef<(typeof import("@vueuse/core"))["useTimeAgoIntl"]>;
    readonly useTimeout: UnwrapRef<(typeof import("@vueuse/core"))["useTimeout"]>;
    readonly useTimeoutFn: UnwrapRef<(typeof import("@vueuse/core"))["useTimeoutFn"]>;
    readonly useTimeoutPoll: UnwrapRef<(typeof import("@vueuse/core"))["useTimeoutPoll"]>;
    readonly useTimestamp: UnwrapRef<(typeof import("@vueuse/core"))["useTimestamp"]>;
    readonly useTitle: UnwrapRef<(typeof import("@vueuse/core"))["useTitle"]>;
    readonly useToNumber: UnwrapRef<(typeof import("@vueuse/core"))["useToNumber"]>;
    readonly useToString: UnwrapRef<(typeof import("@vueuse/core"))["useToString"]>;
    readonly useToast: UnwrapRef<
      (typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.8.1_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_913a7064fdeb5a7a8ca3c073e7097112/node_modules/@nuxt/ui/dist/runtime/composables/useToast"))["useToast"]
    >;
    readonly useToggle: UnwrapRef<(typeof import("@vueuse/core"))["useToggle"]>;
    readonly useTransition: UnwrapRef<(typeof import("@vueuse/core"))["useTransition"]>;
    readonly useTriggerHardcoverSync: UnwrapRef<
      (typeof import("./composables/mutations/useSettingsMutations"))["useTriggerHardcoverSync"]
    >;
    readonly useUpdateProfile: UnwrapRef<
      (typeof import("./composables/mutations/useAccountMutations"))["useUpdateProfile"]
    >;
    readonly useUpload: UnwrapRef<(typeof import("./composables/useUpload"))["useUpload"]>;
    readonly useUrlSearchParams: UnwrapRef<(typeof import("@vueuse/core"))["useUrlSearchParams"]>;
    readonly useUserMedia: UnwrapRef<(typeof import("@vueuse/core"))["useUserMedia"]>;
    readonly useUsersQuery: UnwrapRef<
      (typeof import("./composables/mutations/useUserMutations"))["useUsersQuery"]
    >;
    readonly useVModel: UnwrapRef<(typeof import("@vueuse/core"))["useVModel"]>;
    readonly useVModels: UnwrapRef<(typeof import("@vueuse/core"))["useVModels"]>;
    readonly useVibrate: UnwrapRef<(typeof import("@vueuse/core"))["useVibrate"]>;
    readonly useVirtualList: UnwrapRef<(typeof import("@vueuse/core"))["useVirtualList"]>;
    readonly useWakeLock: UnwrapRef<(typeof import("@vueuse/core"))["useWakeLock"]>;
    readonly useWebNotification: UnwrapRef<(typeof import("@vueuse/core"))["useWebNotification"]>;
    readonly useWebSocket: UnwrapRef<(typeof import("@vueuse/core"))["useWebSocket"]>;
    readonly useWebWorker: UnwrapRef<(typeof import("@vueuse/core"))["useWebWorker"]>;
    readonly useWebWorkerFn: UnwrapRef<(typeof import("@vueuse/core"))["useWebWorkerFn"]>;
    readonly useWindowFocus: UnwrapRef<(typeof import("@vueuse/core"))["useWindowFocus"]>;
    readonly useWindowScroll: UnwrapRef<(typeof import("@vueuse/core"))["useWindowScroll"]>;
    readonly useWindowSize: UnwrapRef<(typeof import("@vueuse/core"))["useWindowSize"]>;
    readonly userAgentIcon: UnwrapRef<(typeof import("./utils/user-agent"))["userAgentIcon"]>;
    readonly watch: UnwrapRef<(typeof import("vue"))["watch"]>;
    readonly watchArray: UnwrapRef<(typeof import("@vueuse/core"))["watchArray"]>;
    readonly watchAtMost: UnwrapRef<(typeof import("@vueuse/core"))["watchAtMost"]>;
    readonly watchDebounced: UnwrapRef<(typeof import("@vueuse/core"))["watchDebounced"]>;
    readonly watchDeep: UnwrapRef<(typeof import("@vueuse/core"))["watchDeep"]>;
    readonly watchEffect: UnwrapRef<(typeof import("vue"))["watchEffect"]>;
    readonly watchIgnorable: UnwrapRef<(typeof import("@vueuse/core"))["watchIgnorable"]>;
    readonly watchImmediate: UnwrapRef<(typeof import("@vueuse/core"))["watchImmediate"]>;
    readonly watchOnce: UnwrapRef<(typeof import("@vueuse/core"))["watchOnce"]>;
    readonly watchPausable: UnwrapRef<(typeof import("@vueuse/core"))["watchPausable"]>;
    readonly watchPostEffect: UnwrapRef<(typeof import("vue"))["watchPostEffect"]>;
    readonly watchSyncEffect: UnwrapRef<(typeof import("vue"))["watchSyncEffect"]>;
    readonly watchThrottled: UnwrapRef<(typeof import("@vueuse/core"))["watchThrottled"]>;
    readonly watchTriggerable: UnwrapRef<(typeof import("@vueuse/core"))["watchTriggerable"]>;
    readonly watchWithFilter: UnwrapRef<(typeof import("@vueuse/core"))["watchWithFilter"]>;
    readonly whenever: UnwrapRef<(typeof import("@vueuse/core"))["whenever"]>;
    readonly yearStringSchema: UnwrapRef<(typeof import("./utils/schemas"))["yearStringSchema"]>;
  }
}
