/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type { _ExtractParamParserType } from "vue-router/experimental";

declare module "vue-router" {
  interface TypesConfig {
    _ParamParsers: {};
    RouteNamedMap: import("vue-router/auto-routes").RouteNamedMap;
    _RouteFileInfoMap: import("vue-router/auto-routes")._RouteFileInfoMap;
  }
}

declare module "vue-router/auto-routes" {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    "/": RouteRecordInfo<"/", "/", Record<never, never>, Record<never, never>, never>;
    "/inbox/": RouteRecordInfo<
      "/inbox/",
      "/inbox",
      Record<never, never>,
      Record<never, never>,
      never
    >;
    "/inbox/[id]": RouteRecordInfo<
      "/inbox/[id]",
      "/inbox/:id",
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      never
    >;
    "/library/": RouteRecordInfo<
      "/library/",
      "/library",
      Record<never, never>,
      Record<never, never>,
      never
    >;
    "/library/[id]": RouteRecordInfo<
      "/library/[id]",
      "/library/:id",
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      never
    >;
    "/reading/": RouteRecordInfo<
      "/reading/",
      "/reading",
      Record<never, never>,
      Record<never, never>,
      never
    >;
    "/reading/[status]": RouteRecordInfo<
      "/reading/[status]",
      "/reading/:status",
      { status: ParamValue<true> },
      { status: ParamValue<false> },
      never
    >;
    "/series/": RouteRecordInfo<
      "/series/",
      "/series",
      Record<never, never>,
      Record<never, never>,
      never
    >;
    "/series/[name]": RouteRecordInfo<
      "/series/[name]",
      "/series/:name",
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      never
    >;
    "/settings": RouteRecordInfo<
      "/settings",
      "/settings",
      Record<never, never>,
      Record<never, never>,
      never
    >;
    "/stats": RouteRecordInfo<
      "/stats",
      "/stats",
      Record<never, never>,
      Record<never, never>,
      never
    >;
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    "src/pages/index.vue": {
      routes: "/";
      views: never;
      pathParamNames: never;
    };
    "src/pages/inbox/index.vue": {
      routes: "/inbox/";
      views: never;
      pathParamNames: never;
    };
    "src/pages/inbox/[id].vue": {
      routes: "/inbox/[id]";
      views: never;
      pathParamNames: "id";
    };
    "src/pages/library/index.vue": {
      routes: "/library/";
      views: never;
      pathParamNames: never;
    };
    "src/pages/library/[id].vue": {
      routes: "/library/[id]";
      views: never;
      pathParamNames: "id";
    };
    "src/pages/reading/index.vue": {
      routes: "/reading/";
      views: never;
      pathParamNames: never;
    };
    "src/pages/reading/[status].vue": {
      routes: "/reading/[status]";
      views: never;
      pathParamNames: "status";
    };
    "src/pages/series/index.vue": {
      routes: "/series/";
      views: never;
      pathParamNames: never;
    };
    "src/pages/series/[name].vue": {
      routes: "/series/[name]";
      views: never;
      pathParamNames: "name";
    };
    "src/pages/settings.vue": {
      routes: "/settings";
      views: never;
      pathParamNames: never;
    };
    "src/pages/stats.vue": {
      routes: "/stats";
      views: never;
      pathParamNames: never;
    };
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info> ? Info["routes"] : keyof RouteNamedMap;
}

export {};
