/**
 * Auto-generate database schema documentation from Drizzle schema.
 *
 * Usage:
 *   vp run -F @libris/docs generate:db
 *
 * OpenAPI spec is handled separately — it's generated by `build:spec` in @libris/api-hono
 * and copied during the docs build step.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const docsDir = resolve(__dirname, "..");
const rootDir = resolve(docsDir, "..");

// ─── Database Schema ────────────────────────────────────────────────────────

interface ColumnInfo {
  sqlName: string;
  type: string;
  notNull: boolean;
  primaryKey: boolean;
  unique: boolean;
  defaultVal: string;
  references: string;
  onDelete: string;
}

function generateDbDocs() {
  const schemaPath = resolve(rootDir, "services/api-hono/src/db/schema.ts");
  const src = readFileSync(schemaPath, "utf-8");

  const lines: string[] = [
    "# Database Schema",
    "",
    "> **Auto-generated** from `services/api-hono/src/db/schema.ts`. Do not edit manually.",
    "> Run `vp run -F @libris/docs generate:db -- --db` to regenerate.",
    "",
    "PostgreSQL with [Drizzle ORM](https://orm.drizzle.team/). Migrations auto-apply on startup via `runMigrations()` in `services/api-hono/src/bootstrap.ts` (the drizzle-orm/postgres-js migrator in `src/db/migrate.ts`); they run before the database pool is created and are skipped when `NODE_ENV=test`.",
    "",
  ];

  // Parse enums
  const enumRegex = /export const (\w+) = pgEnum\("(\w+)", \[([^\]]+)\]\)/g;
  const enums: { name: string; sqlName: string; values: string[] }[] = [];
  let match: RegExpExecArray | null;
  while ((match = enumRegex.exec(src)) !== null) {
    const values = match[3]
      .split(",")
      .map((v: string) => v.trim().replace(/['"]/g, ""))
      .filter(Boolean);
    enums.push({ name: match[1], sqlName: match[2], values });
  }

  if (enums.length > 0) {
    lines.push("## Enums", "");
    for (const e of enums) {
      lines.push(`### \`${e.sqlName}\``, "");
      lines.push(`Values: ${e.values.map((v) => `\`${v}\``).join(", ")}`, "");
    }
  }

  // Parse tables by finding pgTable calls and extracting the column block
  interface IndexInfo {
    name: string;
    unique: boolean;
    gin: boolean;
  }
  const tables: { sqlName: string; columns: ColumnInfo[]; indexes: IndexInfo[] }[] = [];
  const tableStartRegex = /export const \w+ = pgTable\(\s*"(\w+)",\s*\{/g;

  while ((match = tableStartRegex.exec(src)) !== null) {
    const sqlName = match[1];
    const blockStart = match.index + match[0].length;

    // Find the matching closing brace by counting braces
    let depth = 1;
    let pos = blockStart;
    while (pos < src.length && depth > 0) {
      if (src[pos] === "{") depth++;
      if (src[pos] === "}") depth--;
      pos++;
    }
    const columnsBlock = src.slice(blockStart, pos - 1);

    // Continue to the matching close paren of pgTable(...) to capture the
    // second argument, where index/constraint definitions live.
    let pdepth = 1;
    let p2 = pos;
    while (p2 < src.length && pdepth > 0) {
      if (src[p2] === "(") pdepth++;
      if (src[p2] === ")") pdepth--;
      p2++;
    }
    const secondArg = src.slice(pos, p2 - 1);
    const indexes: IndexInfo[] = [];
    const idxRe = /(uniqueIndex|index)\(\s*["']([^"']+)["']\s*\)([^,]*)/g;
    let im: RegExpExecArray | null;
    while ((im = idxRe.exec(secondArg)) !== null) {
      indexes.push({
        name: im[2],
        unique: im[1] === "uniqueIndex",
        gin: /\.using\(\s*["']gin["']/.test(im[3]),
      });
    }

    // Parse line by line
    const columns = parseColumnsLineByLine(columnsBlock);
    tables.push({ sqlName, columns, indexes });
  }

  lines.push("## Tables", "");

  // Only Libris' own tables. Better Auth owns `users`, `sessions`, `accounts`,
  // `verifications` and `api_keys` (see src/db/auth-schema.ts); this generator
  // reads schema.ts alone, so those are documented by Better Auth rather than
  // here.
  const tableDescriptions: Record<string, string> = {
    books: "Main book records with status, metadata, and the full-text search vector",
    book_files: "Physical file storage per book (format, checksums, content hashes, paths)",
    book_metadata_candidates:
      "Metadata candidates per book and source (file, hardcover) shown during review",
    reading_progress: "Current KoReader/KoSync reading position per document and device",
    reading_progress_history: "Append-only history of reading-progress snapshots",
    reading_aggregate:
      "Per-(user, book) reading lifecycle: effective status plus started/finished/paused dates and any manual override",
    service_credentials:
      "Per-user Hardcover API token (sealed, reversible). `username` is a label, not an identity — it is not unique across users",
    kosync_credentials:
      "Per-user KoSync login: the username KOReader sends plus a sha256 of the secret it puts on the wire",
    app_settings: "Global key/value application settings (e.g. Hardcover metadata/sync toggles)",
    upload_registry:
      "Checksum → uploader (user) ownership mapping consumed by the book-detected worker",
    hardcover_sync_log: "Per-(user, book) Hardcover sync tracking and last status",
  };

  lines.push("| Table | Description |");
  lines.push("| ----- | ----------- |");
  for (const t of tables) {
    lines.push(`| \`${t.sqlName}\` | ${tableDescriptions[t.sqlName] || ""} |`);
  }
  lines.push("");

  for (const t of tables) {
    lines.push(`### \`${t.sqlName}\``, "");
    lines.push("| Column | Type | Nullable | Default | Notes |");
    lines.push("| ------ | ---- | -------- | ------- | ----- |");

    for (const col of t.columns) {
      // PRIMARY KEY columns are NOT NULL even without an explicit .notNull().
      const nullable = col.notNull || col.primaryKey ? "No" : "Yes";
      const notes: string[] = [];
      if (col.primaryKey) notes.push("PK");
      if (col.unique) notes.push("Unique");
      if (col.references) {
        notes.push(
          col.onDelete
            ? `FK → \`${col.references}\` (ON DELETE ${col.onDelete})`
            : `FK → \`${col.references}\``,
        );
      }
      lines.push(
        `| \`${col.sqlName}\` | ${col.type} | ${nullable} | ${col.defaultVal || "—"} | ${notes.join(", ")} |`,
      );
    }
    lines.push("");

    if (t.indexes.length > 0) {
      const idxList = t.indexes
        .map((i) => `\`${i.name}\`${i.unique ? " (unique)" : ""}${i.gin ? " (GIN)" : ""}`)
        .join(", ");
      lines.push(`**Indexes:** ${idxList}`, "");
    }
  }

  // Notes
  lines.push("## Notes", "");
  lines.push(
    "- `books.language` holds a canonical lowercase ISO 639-1 code (e.g. `en`, `fr`); arbitrary input is normalized by `services/api-hono/src/lib/languages.ts`.",
    "- `book_files.format`, `book_metadata_candidates.source`, `service_credentials.service`, and `hardcover_sync_log.last_status` are free-text columns (not Postgres enums) even though they hold format/source/status-like values.",
    "- `books.search_vector` is excluded from all API responses — the API selects the `bookColumns` projection, which omits it.",
    "- `reading_progress`, `reading_progress_history`, and `reading_aggregate` use `ON DELETE SET NULL` on `book_id` so reading history survives a book deletion, while their `user_id` cascades (or is set null for history).",
    "- Better Auth owns `users`, `sessions`, `accounts`, `verifications` and `api_keys` — they are declared in `services/api-hono/src/db/auth-schema.ts` and are not listed above.",
    "- The trigram indexes (`*_trgm_idx`) require the `pg_trgm` extension; the full-text `*_search_vector_idx` is a GIN index over the generated `tsvector`.",
    "",
  );

  // Relationships diagram
  lines.push("## Relationships", "");
  lines.push("```mermaid");
  lines.push("erDiagram");
  for (const t of tables) {
    for (const col of t.columns) {
      if (col.references) {
        const refTable = col.references.replace(/\..*/, "");
        lines.push(`    ${refTable} ||--o{ ${t.sqlName} : "has many"`);
      }
    }
  }
  lines.push("```");
  lines.push("");

  writeFileSync(resolve(docsDir, "database.md"), lines.join("\n"));
  console.log("✓ Generated database.md from Drizzle schema");
}

function parseColumnsLineByLine(block: string): ColumnInfo[] {
  const columns: ColumnInfo[] = [];

  // Join continuation lines: a column definition starts with `propName:` and
  // may span multiple lines until the next `propName:` or end of block.
  const joined: string[] = [];
  for (const rawLine of block.split("\n")) {
    const trimmed = rawLine.trim();
    if (!trimmed || trimmed.startsWith("//")) continue;
    if (/^\w+:\s*\w+\(/.test(trimmed)) {
      joined.push(trimmed);
    } else if (joined.length > 0) {
      joined[joined.length - 1] += " " + trimmed;
    }
  }

  for (const line of joined) {
    // Match: propName: type("sql_name" ...) or propName: enumVar("sql_name")
    const colMatch = line.match(/^(\w+):\s*(\w+)\(([^)]*)\)/);
    if (!colMatch) continue;

    const propName = colMatch[1];
    const typeCall = colMatch[2];
    const typeArgs = colMatch[3];

    // Skip if this looks like a function/method, not a column
    if (["index", "unique"].includes(propName)) continue;

    // Get SQL column name
    const sqlNameMatch = typeArgs.match(/["']([^"']+)["']/);
    const sqlName = sqlNameMatch ? sqlNameMatch[1] : propName;

    // Determine type
    let type: string;
    const baseTypes: Record<string, string> = {
      uuid: "uuid",
      text: "text",
      integer: "integer",
      bigint: "bigint",
      numeric: "numeric",
      timestamp: "timestamptz",
      jsonb: "jsonb",
      tsvector: "tsvector",
    };

    if (baseTypes[typeCall]) {
      type = baseTypes[typeCall];
    } else if (typeCall.endsWith("Enum")) {
      // e.g. bookStatusEnum → enum(book_status), readingStatusEnum → enum(reading_status)
      const sqlEnumName = typeCall
        .replace(/Enum$/, "")
        .replace(/([A-Z])/g, "_$1")
        .toLowerCase()
        .replace(/^_/, "");
      type = `enum(${sqlEnumName})`;
    } else if (typeCall === "customType") {
      type = "tsvector";
    } else {
      type = typeCall;
    }

    // Check precision in args
    const precMatch = typeArgs.match(/precision:\s*(\d+),\s*scale:\s*(\d+)/);
    if (precMatch) type = `numeric(${precMatch[1]},${precMatch[2]})`;

    // Check withTimezone
    if (typeArgs.includes("withTimezone")) type = "timestamptz";

    // Check for array (rest of the chain on same line)
    if (line.includes(".array()")) type += "[]";

    // Check chain modifiers on this line
    const notNull = line.includes(".notNull()");
    const primaryKey = line.includes(".primaryKey()");
    const unique = line.includes(".unique()") && !line.includes("unique(");

    // Default
    let defaultVal = "";
    if (line.includes(".defaultRandom()")) {
      defaultVal = "random()";
    } else if (line.includes(".defaultNow()")) {
      defaultVal = "now()";
    } else {
      const defMatch = line.match(/\.default\(([^)]+)\)/);
      if (defMatch) {
        const val = defMatch[1].trim();
        const sqlLit = val.match(/sql`([^`]+)`/);
        if (sqlLit) {
          defaultVal = sqlLit[1];
        } else {
          defaultVal = val.replace(/['"]/g, "");
        }
      }
    }

    // References + on-delete behaviour
    let references = "";
    let onDelete = "";
    const refMatch = line.match(/\.references\(\(\)\s*=>\s*(\w+)\.(\w+)/);
    if (refMatch) {
      references = `${refMatch[1]}.${refMatch[2]}`;
    }
    const odMatch =
      line.match(/onDelete:\s*["']([^"']+)["']/) || line.match(/\.onDelete\(["']([^"']+)["']\)/);
    if (odMatch) onDelete = odMatch[1];

    columns.push({
      sqlName,
      type,
      notNull,
      primaryKey,
      unique,
      defaultVal,
      references,
      onDelete,
    });
  }

  return columns;
}

// ─── Main ───────────────────────────────────────────────────────────────────

generateDbDocs();
console.log("Done!");
